import pg from "pg";

const { Pool } = pg;

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL must be set");
}

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

type FirmSeed = {
  rank: number;
  name: string;
  hq_city: string;
  hq_state: string;
  website_url: string;
  careers_url: string;
  ats_type?: string;
  ats_url?: string;
};

const FIRMS: FirmSeed[] = [
  // ─── ranks 1-25 already seeded; listed here so re-running is safe ───────────
  { rank: 1, name: "Deloitte", hq_city: "New York", hq_state: "NY", website_url: "https://www.deloitte.com", careers_url: "https://www.deloitte.com/us/en/careers.html" },
  { rank: 2, name: "PwC", hq_city: "New York", hq_state: "NY", website_url: "https://www.pwc.com", careers_url: "https://www.pwc.com/us/en/careers.html" },
  { rank: 3, name: "EY", hq_city: "New York", hq_state: "NY", website_url: "https://www.ey.com", careers_url: "https://www.ey.com/en_us/careers" },
  { rank: 4, name: "KPMG", hq_city: "New York", hq_state: "NY", website_url: "https://kpmg.com", careers_url: "https://kpmg.com/us/en/careers.html" },
  { rank: 5, name: "RSM", hq_city: "Chicago", hq_state: "IL", website_url: "https://rsmus.com", careers_url: "https://rsmus.com/careers", ats_type: "workday", ats_url: "https://rsm.wd5.myworkdayjobs.com/ExperiencedProfessionals" },
  { rank: 6, name: "Baker Tilly", hq_city: "Chicago", hq_state: "IL", website_url: "https://www.bakertilly.com", careers_url: "https://www.bakertilly.com/careers" },
  { rank: 7, name: "CBIZ", hq_city: "Cleveland", hq_state: "OH", website_url: "https://www.cbiz.com", careers_url: "https://www.cbiz.com/careers" },
  { rank: 8, name: "BDO USA", hq_city: "Chicago", hq_state: "IL", website_url: "https://www.bdo.com", careers_url: "https://www.bdo.com/careers", ats_type: "workday", ats_url: "https://bdo.wd1.myworkdayjobs.com/BDO" },
  { rank: 9, name: "Grant Thornton", hq_city: "Chicago", hq_state: "IL", website_url: "https://www.grantthornton.com", careers_url: "https://www.grantthornton.com/careers", ats_type: "workday", ats_url: "https://grantthornton.wd1.myworkdayjobs.com/GrantThornton" },
  { rank: 10, name: "Forvis Mazars", hq_city: "Springfield", hq_state: "MO", website_url: "https://www.forvismazars.us", careers_url: "https://www.forvismazars.us/careers" },
  { rank: 11, name: "CLA", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.claconnect.com", careers_url: "https://www.claconnect.com/careers" },
  { rank: 12, name: "Crowe", hq_city: "Chicago", hq_state: "IL", website_url: "https://www.crowe.com", careers_url: "https://www.crowe.com/careers", ats_type: "workday", ats_url: "https://crowe.wd1.myworkdayjobs.com/crowecareers" },
  { rank: 13, name: "Plante Moran", hq_city: "Southfield", hq_state: "MI", website_url: "https://www.plantemoran.com", careers_url: "https://www.plantemoran.com/careers" },
  { rank: 14, name: "CohnReznick", hq_city: "New York", hq_state: "NY", website_url: "https://www.cohnreznick.com", careers_url: "https://www.cohnreznick.com/careers" },
  { rank: 15, name: "Moss Adams", hq_city: "Seattle", hq_state: "WA", website_url: "https://www.mossadams.com", careers_url: "https://www.mossadams.com/careers", ats_type: "workday", ats_url: "https://mossadams.wd1.myworkdayjobs.com/MossAdams" },
  { rank: 16, name: "Marcum", hq_city: "New York", hq_state: "NY", website_url: "https://www.marcumllp.com", careers_url: "https://www.marcumllp.com/careers" },
  { rank: 17, name: "EisnerAmper", hq_city: "New York", hq_state: "NY", website_url: "https://www.eisneramper.com", careers_url: "https://www.eisneramper.com/careers" },
  { rank: 18, name: "Cherry Bekaert", hq_city: "Richmond", hq_state: "VA", website_url: "https://www.cbh.com", careers_url: "https://www.cbh.com/careers" },
  { rank: 19, name: "Citrin Cooperman", hq_city: "New York", hq_state: "NY", website_url: "https://www.citrincooperman.com", careers_url: "https://www.citrincooperman.com/careers" },
  { rank: 20, name: "PKF O'Connor Davies", hq_city: "Harrison", hq_state: "NY", website_url: "https://www.pkfod.com", careers_url: "https://www.pkfod.com/careers" },
  { rank: 21, name: "Eide Bailly", hq_city: "Fargo", hq_state: "ND", website_url: "https://www.eidebailly.com", careers_url: "https://www.eidebailly.com/careers", ats_type: "workday", ats_url: "https://eidebailly.wd1.myworkdayjobs.com/EideBailly" },
  { rank: 22, name: "Armanino", hq_city: "San Ramon", hq_state: "CA", website_url: "https://www.armanino.com", careers_url: "https://www.armanino.com/careers" },
  { rank: 23, name: "BPM LLP", hq_city: "San Francisco", hq_state: "CA", website_url: "https://www.bpm.com", careers_url: "https://www.bpm.com/careers", ats_type: "lever", ats_url: "https://jobs.lever.co/bpmcpa" },
  { rank: 24, name: "Dixon Hughes Goodman", hq_city: "Charlotte", hq_state: "NC", website_url: "https://www.dhg.com", careers_url: "https://www.dhg.com/careers" },
  { rank: 25, name: "Berkowitz Pollack Brant", hq_city: "Miami", hq_state: "FL", website_url: "https://www.bpbcpa.com", careers_url: "https://www.bpbcpa.com/careers" },
  // ─── ranks 26–100 ────────────────────────────────────────────────────────────
  { rank: 26, name: "Wipfli LLP", hq_city: "Milwaukee", hq_state: "WI", website_url: "https://www.wipfli.com", careers_url: "https://www.wipfli.com/careers" },
  { rank: 27, name: "Weaver", hq_city: "Fort Worth", hq_state: "TX", website_url: "https://www.weaver.com", careers_url: "https://www.weaver.com/careers" },
  { rank: 28, name: "Aprio", hq_city: "Atlanta", hq_state: "GA", website_url: "https://www.aprio.com", careers_url: "https://www.aprio.com/careers" },
  { rank: 29, name: "Sikich LLP", hq_city: "Naperville", hq_state: "IL", website_url: "https://www.sikich.com", careers_url: "https://www.sikich.com/careers" },
  { rank: 30, name: "Carr, Riggs & Ingram", hq_city: "Enterprise", hq_state: "AL", website_url: "https://www.cricpa.com", careers_url: "https://www.cricpa.com/careers" },
  { rank: 31, name: "Withum", hq_city: "Princeton", hq_state: "NJ", website_url: "https://www.withum.com", careers_url: "https://www.withum.com/careers" },
  { rank: 32, name: "Whitley Penn", hq_city: "Fort Worth", hq_state: "TX", website_url: "https://www.whitleypenn.com", careers_url: "https://www.whitleypenn.com/careers" },
  { rank: 33, name: "RubinBrown", hq_city: "St. Louis", hq_state: "MO", website_url: "https://www.rubinbrown.com", careers_url: "https://www.rubinbrown.com/careers" },
  { rank: 34, name: "Frazier & Deeter", hq_city: "Atlanta", hq_state: "GA", website_url: "https://www.frazierdeeter.com", careers_url: "https://www.frazierdeeter.com/careers" },
  { rank: 35, name: "Elliott Davis", hq_city: "Greenville", hq_state: "SC", website_url: "https://www.elliottdavis.com", careers_url: "https://www.elliottdavis.com/careers" },
  { rank: 36, name: "Rehmann", hq_city: "Troy", hq_state: "MI", website_url: "https://www.rehmann.com", careers_url: "https://www.rehmann.com/careers" },
  { rank: 37, name: "KSM (Katz, Sapper & Miller)", hq_city: "Indianapolis", hq_state: "IN", website_url: "https://www.ksmcpa.com", careers_url: "https://www.ksmcpa.com/careers" },
  { rank: 38, name: "Rea & Associates", hq_city: "Dublin", hq_state: "OH", website_url: "https://www.reacpa.com", careers_url: "https://www.reacpa.com/careers" },
  { rank: 39, name: "Postlethwaite & Netterville", hq_city: "Baton Rouge", hq_state: "LA", website_url: "https://www.pncpa.com", careers_url: "https://www.pncpa.com/careers" },
  { rank: 40, name: "HORNE LLP", hq_city: "Ridgeland", hq_state: "MS", website_url: "https://www.hornellp.com", careers_url: "https://www.hornellp.com/careers" },
  { rank: 41, name: "Clark Nuber", hq_city: "Bellevue", hq_state: "WA", website_url: "https://www.clarknuber.com", careers_url: "https://www.clarknuber.com/careers" },
  { rank: 42, name: "GBQ Partners", hq_city: "Columbus", hq_state: "OH", website_url: "https://www.gbq.com", careers_url: "https://www.gbq.com/careers" },
  { rank: 43, name: "The Bonadio Group", hq_city: "Rochester", hq_state: "NY", website_url: "https://www.bonadio.com", careers_url: "https://www.bonadio.com/careers" },
  { rank: 44, name: "Smith & Howard", hq_city: "Atlanta", hq_state: "GA", website_url: "https://www.smith-howard.com", careers_url: "https://www.smith-howard.com/careers" },
  { rank: 45, name: "Lurie LLP", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.luriellp.com", careers_url: "https://www.luriellp.com/careers" },
  { rank: 46, name: "Kaufman Rossin", hq_city: "Miami", hq_state: "FL", website_url: "https://www.kaufmanrossin.com", careers_url: "https://www.kaufmanrossin.com/careers" },
  { rank: 47, name: "Windham Brannon", hq_city: "Atlanta", hq_state: "GA", website_url: "https://www.windhambrannon.com", careers_url: "https://www.windhambrannon.com/careers" },
  { rank: 48, name: "Novogradac & Company", hq_city: "San Francisco", hq_state: "CA", website_url: "https://www.novoco.com", careers_url: "https://www.novoco.com/careers" },
  { rank: 49, name: "Grassi & Co", hq_city: "Jericho", hq_state: "NY", website_url: "https://www.grassicpas.com", careers_url: "https://www.grassicpas.com/careers" },
  { rank: 50, name: "Sax LLP", hq_city: "Parsippany", hq_state: "NJ", website_url: "https://www.saxllp.com", careers_url: "https://www.saxllp.com/careers" },
  { rank: 51, name: "Schneider Downs", hq_city: "Pittsburgh", hq_state: "PA", website_url: "https://www.schneiderdowns.com", careers_url: "https://www.schneiderdowns.com/careers" },
  { rank: 52, name: "Redpath and Company", hq_city: "St. Paul", hq_state: "MN", website_url: "https://www.redpathcpas.com", careers_url: "https://www.redpathcpas.com/careers" },
  { rank: 53, name: "Sensiba", hq_city: "Pleasanton", hq_state: "CA", website_url: "https://www.sensiba.com", careers_url: "https://www.sensiba.com/careers" },
  { rank: 54, name: "Friedman LLP", hq_city: "New York", hq_state: "NY", website_url: "https://www.friedmanllp.com", careers_url: "https://www.friedmanllp.com/careers" },
  { rank: 55, name: "SingerLewak", hq_city: "Los Angeles", hq_state: "CA", website_url: "https://www.singerlewak.com", careers_url: "https://www.singerlewak.com/careers" },
  { rank: 56, name: "Hogan Taylor", hq_city: "Tulsa", hq_state: "OK", website_url: "https://www.hogantaylor.com", careers_url: "https://www.hogantaylor.com/careers" },
  { rank: 57, name: "Warren Averett", hq_city: "Birmingham", hq_state: "AL", website_url: "https://www.warrenaverett.com", careers_url: "https://www.warrenaverett.com/careers" },
  { rank: 58, name: "Anders CPAs & Advisors", hq_city: "St. Louis", hq_state: "MO", website_url: "https://www.anderscpa.com", careers_url: "https://www.anderscpa.com/careers" },
  { rank: 59, name: "Mauldin & Jenkins", hq_city: "Albany", hq_state: "GA", website_url: "https://www.mauldinjenkins.com", careers_url: "https://www.mauldinjenkins.com/careers" },
  { rank: 60, name: "Dean Dorton", hq_city: "Lexington", hq_state: "KY", website_url: "https://www.deandorton.com", careers_url: "https://www.deandorton.com/careers" },
  { rank: 61, name: "Brown, Edwards & Company", hq_city: "Roanoke", hq_state: "VA", website_url: "https://www.becpas.com", careers_url: "https://www.becpas.com/careers" },
  { rank: 62, name: "GreerWalker", hq_city: "Charlotte", hq_state: "NC", website_url: "https://www.greerwalker.com", careers_url: "https://www.greerwalker.com/careers" },
  { rank: 63, name: "Stout", hq_city: "Chicago", hq_state: "IL", website_url: "https://www.stout.com", careers_url: "https://www.stout.com/careers" },
  { rank: 64, name: "Freed Maxick", hq_city: "Buffalo", hq_state: "NY", website_url: "https://www.freedmaxick.com", careers_url: "https://www.freedmaxick.com/careers" },
  { rank: 65, name: "Berdon LLP", hq_city: "New York", hq_state: "NY", website_url: "https://www.berdonllp.com", careers_url: "https://www.berdonllp.com/careers" },
  { rank: 66, name: "Aronson LLC", hq_city: "Rockville", hq_state: "MD", website_url: "https://www.aronsonllc.com", careers_url: "https://www.aronsonllc.com/careers" },
  { rank: 67, name: "Cohen & Company", hq_city: "Cleveland", hq_state: "OH", website_url: "https://www.cohencpa.com", careers_url: "https://www.cohencpa.com/careers" },
  { rank: 68, name: "Richey May", hq_city: "Greenwood Village", hq_state: "CO", website_url: "https://www.richeymay.com", careers_url: "https://www.richeymay.com/careers" },
  { rank: 69, name: "Holthouse Carlin & Van Trigt", hq_city: "Los Angeles", hq_state: "CA", website_url: "https://www.hcvt.com", careers_url: "https://www.hcvt.com/careers" },
  { rank: 70, name: "Blum Shapiro", hq_city: "West Hartford", hq_state: "CT", website_url: "https://www.blumshapiro.com", careers_url: "https://www.blumshapiro.com/careers" },
  { rank: 71, name: "Baker Newman Noyes", hq_city: "Portland", hq_state: "ME", website_url: "https://www.bnncpa.com", careers_url: "https://www.bnncpa.com/careers" },
  { rank: 72, name: "WilkinGuttenplan", hq_city: "East Brunswick", hq_state: "NJ", website_url: "https://www.wgcpas.com", careers_url: "https://www.wgcpas.com/careers" },
  { rank: 73, name: "Kreischer Miller", hq_city: "Horsham", hq_state: "PA", website_url: "https://www.kmco.com", careers_url: "https://www.kmco.com/careers" },
  { rank: 74, name: "Tonneson + Co", hq_city: "Wakefield", hq_state: "MA", website_url: "https://www.tonneson.com", careers_url: "https://www.tonneson.com/careers" },
  { rank: 75, name: "Gelman, Rosenberg & Freedman", hq_city: "Bethesda", hq_state: "MD", website_url: "https://www.grfcpa.com", careers_url: "https://www.grfcpa.com/careers" },
  { rank: 76, name: "Hall & Company", hq_city: "Irvine", hq_state: "CA", website_url: "https://www.hallcpa.com", careers_url: "https://www.hallcpa.com/careers" },
  { rank: 77, name: "Larson & Company", hq_city: "Provo", hq_state: "UT", website_url: "https://www.larsoncpa.com", careers_url: "https://www.larsoncpa.com/careers" },
  { rank: 78, name: "James Moore & Co.", hq_city: "Gainesville", hq_state: "FL", website_url: "https://www.jmco.com", careers_url: "https://www.jmco.com/careers" },
  { rank: 79, name: "Anchin", hq_city: "New York", hq_state: "NY", website_url: "https://www.anchin.com", careers_url: "https://www.anchin.com/careers" },
  { rank: 80, name: "Doeren Mayhew", hq_city: "Troy", hq_state: "MI", website_url: "https://www.doeren.com", careers_url: "https://www.doeren.com/careers" },
  { rank: 81, name: "Honkamp", hq_city: "Dubuque", hq_state: "IA", website_url: "https://www.honkamp.com", careers_url: "https://www.honkamp.com/careers" },
  { rank: 82, name: "Maner Costerisan", hq_city: "Lansing", hq_state: "MI", website_url: "https://www.manercpa.com", careers_url: "https://www.manercpa.com/careers" },
  { rank: 83, name: "Clayton & McKervey", hq_city: "Troy", hq_state: "MI", website_url: "https://www.claytonmckervey.com", careers_url: "https://www.claytonmckervey.com/careers" },
  { rank: 84, name: "Jones & Roth", hq_city: "Eugene", hq_state: "OR", website_url: "https://www.jrcpa.com", careers_url: "https://www.jrcpa.com/careers" },
  { rank: 85, name: "Glenn Burdette", hq_city: "San Luis Obispo", hq_state: "CA", website_url: "https://www.glennburdette.com", careers_url: "https://www.glennburdette.com/careers" },
  { rank: 86, name: "Grimbleby Coleman", hq_city: "Modesto", hq_state: "CA", website_url: "https://www.gccpas.com", careers_url: "https://www.gccpas.com/careers" },
  { rank: 87, name: "Haskell & White", hq_city: "Irvine", hq_state: "CA", website_url: "https://www.hwcpa.com", careers_url: "https://www.hwcpa.com/careers" },
  { rank: 88, name: "Goldin Peiser & Peiser", hq_city: "Dallas", hq_state: "TX", website_url: "https://www.gppcpa.com", careers_url: "https://www.gppcpa.com/careers" },
  { rank: 89, name: "Ellin & Tucker", hq_city: "Baltimore", hq_state: "MD", website_url: "https://www.ellintucker.com", careers_url: "https://www.ellintucker.com/careers" },
  { rank: 90, name: "Gorfine, Schiller & Gardyn", hq_city: "Owings Mills", hq_state: "MD", website_url: "https://www.gsg.cpa", careers_url: "https://www.gsg.cpa/careers" },
  { rank: 91, name: "Tanner LLC", hq_city: "Salt Lake City", hq_state: "UT", website_url: "https://www.tannerlc.com", careers_url: "https://www.tannerlc.com/careers" },
  { rank: 92, name: "Squire & Company", hq_city: "Orem", hq_state: "UT", website_url: "https://www.squire.com", careers_url: "https://www.squire.com/careers" },
  { rank: 93, name: "Cornwell Jackson", hq_city: "Southlake", hq_state: "TX", website_url: "https://www.cornwalljackson.com", careers_url: "https://www.cornwalljackson.com/careers" },
  { rank: 94, name: "dbbmckennon", hq_city: "Newport Beach", hq_state: "CA", website_url: "https://www.dbbm.com", careers_url: "https://www.dbbm.com/careers" },
  { rank: 95, name: "DZH Phillips", hq_city: "San Francisco", hq_state: "CA", website_url: "https://www.dzhphillips.com", careers_url: "https://www.dzhphillips.com/careers" },
  { rank: 96, name: "Calvetti Ferguson", hq_city: "Houston", hq_state: "TX", website_url: "https://www.calvettiferguson.com", careers_url: "https://www.calvettiferguson.com/careers" },
  { rank: 97, name: "Martin Starnes & Associates", hq_city: "Hickory", hq_state: "NC", website_url: "https://www.martinstarnes.com", careers_url: "https://www.martinstarnes.com/careers" },
  { rank: 98, name: "Heinfeld, Meech & Co.", hq_city: "Tucson", hq_state: "AZ", website_url: "https://www.heinfeldmeech.com", careers_url: "https://www.heinfeldmeech.com/careers" },
  { rank: 99, name: "Kramer & Frank", hq_city: "Kansas City", hq_state: "MO", website_url: "https://www.kramerfrank.com", careers_url: "https://www.kramerfrank.com/careers" },
  { rank: 100, name: "Bernard Robinson & Co", hq_city: "Greensboro", hq_state: "NC", website_url: "https://www.brcllp.com", careers_url: "https://www.brcllp.com/careers" },
  // ─── ranks 101–200 ───────────────────────────────────────────────────────────
  { rank: 101, name: "Morrison, Brown, Argiz & Farra", hq_city: "Miami", hq_state: "FL", website_url: "https://www.mbafcpa.com", careers_url: "https://www.mbafcpa.com/careers" },
  { rank: 102, name: "Goldenberg Rosenthal", hq_city: "Blue Bell", hq_state: "PA", website_url: "https://www.grllp.com", careers_url: "https://www.grllp.com/careers" },
  { rank: 103, name: "Wouch, Maloney & Co.", hq_city: "Horsham", hq_state: "PA", website_url: "https://www.wmcpa.com", careers_url: "https://www.wmcpa.com/careers" },
  { rank: 104, name: "True Partners Consulting", hq_city: "Chicago", hq_state: "IL", website_url: "https://www.truepartnersconsulting.com", careers_url: "https://www.truepartnersconsulting.com/careers" },
  { rank: 105, name: "Untracht Early", hq_city: "Florham Park", hq_state: "NJ", website_url: "https://www.untrachtearly.com", careers_url: "https://www.untrachtearly.com/careers" },
  { rank: 106, name: "Mayer Hoffman McCann", hq_city: "Leawood", hq_state: "KS", website_url: "https://www.mhm-pc.com", careers_url: "https://www.mhm-pc.com/careers" },
  { rank: 107, name: "Gelman, Rosenberg & Freedman CPAs", hq_city: "Bethesda", hq_state: "MD", website_url: "https://www.grfcpa.com", careers_url: "https://www.grfcpa.com/careers" },
  { rank: 108, name: "Aronson & Company", hq_city: "Rockville", hq_state: "MD", website_url: "https://www.aronsonllc.com", careers_url: "https://www.aronsonllc.com/careers" },
  { rank: 109, name: "Cohen & Co", hq_city: "Cleveland", hq_state: "OH", website_url: "https://www.cohencpa.com", careers_url: "https://www.cohencpa.com/careers" },
  { rank: 110, name: "Yohalem Gillman & Co", hq_city: "New York", hq_state: "NY", website_url: "https://www.yohalemgillman.com", careers_url: "https://www.yohalemgillman.com/careers" },
  { rank: 111, name: "Aldridge, Borden & Company", hq_city: "Montgomery", hq_state: "AL", website_url: "https://www.aldridgeborden.com", careers_url: "https://www.aldridgeborden.com/careers" },
  { rank: 112, name: "Harding, Shymanski & Company", hq_city: "Evansville", hq_state: "IN", website_url: "https://www.hscpas.com", careers_url: "https://www.hscpas.com/careers" },
  { rank: 113, name: "Hantzmon Wiebel", hq_city: "Charlottesville", hq_state: "VA", website_url: "https://www.hwtcpa.com", careers_url: "https://www.hwtcpa.com/careers" },
  { rank: 114, name: "Liggett & Webb", hq_city: "Dothan", hq_state: "AL", website_url: "https://www.lwcpas.com", careers_url: "https://www.lwcpas.com/careers" },
  { rank: 115, name: "K·Coe Isom", hq_city: "Wichita", hq_state: "KS", website_url: "https://www.kcoeisom.com", careers_url: "https://www.kcoeisom.com/careers" },
  { rank: 116, name: "Donahue, Giroux, Brown, Haasl & Maukonen", hq_city: "St. Cloud", hq_state: "MN", website_url: "https://www.dgbhm.com", careers_url: "https://www.dgbhm.com/careers" },
  { rank: 117, name: "Faw Casson & Co", hq_city: "Dover", hq_state: "DE", website_url: "https://www.fawcasson.com", careers_url: "https://www.fawcasson.com/careers" },
  { rank: 118, name: "Gorfine Schiller Gardyn", hq_city: "Owings Mills", hq_state: "MD", website_url: "https://www.gsgcpa.com", careers_url: "https://www.gsgcpa.com/careers" },
  { rank: 119, name: "Brown Smith Wallace", hq_city: "St. Louis", hq_state: "MO", website_url: "https://www.bswllc.com", careers_url: "https://www.bswllc.com/careers" },
  { rank: 120, name: "Larimer CPAs", hq_city: "Fort Collins", hq_state: "CO", website_url: "https://www.larimercpas.com", careers_url: "https://www.larimercpas.com/careers" },
  { rank: 121, name: "Maner Costerisan CPAs", hq_city: "Lansing", hq_state: "MI", website_url: "https://www.manercpa.com", careers_url: "https://www.manercpa.com/careers" },
  { rank: 122, name: "Smith Schafer & Associates", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.smithschafer.com", careers_url: "https://www.smithschafer.com/careers" },
  { rank: 123, name: "Hogan Taylor LLP", hq_city: "Tulsa", hq_state: "OK", website_url: "https://www.hogantaylor.com", careers_url: "https://www.hogantaylor.com/careers" },
  { rank: 124, name: "LGA LLP", hq_city: "Burlington", hq_state: "MA", website_url: "https://www.lgacpa.com", careers_url: "https://www.lgacpa.com/careers" },
  { rank: 125, name: "Mason & Rich Professional Association", hq_city: "Concord", hq_state: "NH", website_url: "https://www.masonrich.com", careers_url: "https://www.masonrich.com/careers" },
  { rank: 126, name: "Isdaner & Company", hq_city: "Bala Cynwyd", hq_state: "PA", website_url: "https://www.isdaner.com", careers_url: "https://www.isdaner.com/careers" },
  { rank: 127, name: "Eide Bailly CPAs", hq_city: "Fargo", hq_state: "ND", website_url: "https://www.eidebailly.com", careers_url: "https://www.eidebailly.com/careers" },
  { rank: 128, name: "McConnell & Jones", hq_city: "Houston", hq_state: "TX", website_url: "https://www.mcconnelljones.com", careers_url: "https://www.mcconnelljones.com/careers" },
  { rank: 129, name: "Carr, Riggs & Ingram CPAs", hq_city: "Enterprise", hq_state: "AL", website_url: "https://www.cricpa.com", careers_url: "https://www.cricpa.com/careers" },
  { rank: 130, name: "WIPFLi Consulting", hq_city: "Milwaukee", hq_state: "WI", website_url: "https://www.wipfli.com", careers_url: "https://www.wipfli.com/careers" },
  { rank: 131, name: "Holthouse Carlin Van Trigt", hq_city: "Los Angeles", hq_state: "CA", website_url: "https://www.hcvt.com", careers_url: "https://www.hcvt.com/careers" },
  { rank: 132, name: "DeJoy, Knauf & Blood", hq_city: "Rochester", hq_state: "NY", website_url: "https://www.dkbllp.com", careers_url: "https://www.dkbllp.com/careers" },
  { rank: 133, name: "William Vaughan Company", hq_city: "Defiance", hq_state: "OH", website_url: "https://www.wvco.com", careers_url: "https://www.wvco.com/careers" },
  { rank: 134, name: "Stancil & Company", hq_city: "Raleigh", hq_state: "NC", website_url: "https://www.stancil.com", careers_url: "https://www.stancil.com/careers" },
  { rank: 135, name: "Causey Demgen & Moore", hq_city: "Denver", hq_state: "CO", website_url: "https://www.cdm-cpa.com", careers_url: "https://www.cdm-cpa.com/careers" },
  { rank: 136, name: "Saltmarsh, Cleaveland & Gund", hq_city: "Pensacola", hq_state: "FL", website_url: "https://www.saltmarshcpa.com", careers_url: "https://www.saltmarshcpa.com/careers" },
  { rank: 137, name: "Berman Hopkins Wright & LaHam", hq_city: "Orlando", hq_state: "FL", website_url: "https://www.bhwl.com", careers_url: "https://www.bhwl.com/careers" },
  { rank: 138, name: "Maloney + Novotny", hq_city: "Cleveland", hq_state: "OH", website_url: "https://www.maloneynovotny.com", careers_url: "https://www.maloneynovotny.com/careers" },
  { rank: 139, name: "Novogradac", hq_city: "San Francisco", hq_state: "CA", website_url: "https://www.novoco.com", careers_url: "https://www.novoco.com/careers" },
  { rank: 140, name: "GHP Horwath", hq_city: "Denver", hq_state: "CO", website_url: "https://www.ghphorwath.com", careers_url: "https://www.ghphorwath.com/careers" },
  { rank: 141, name: "Thomas, Wirig, Doll & Co.", hq_city: "Chico", hq_state: "CA", website_url: "https://www.twdcpa.com", careers_url: "https://www.twdcpa.com/careers" },
  { rank: 142, name: "Vrakas CPAs + Advisors", hq_city: "Brookfield", hq_state: "WI", website_url: "https://www.vrakas.com", careers_url: "https://www.vrakas.com/careers" },
  { rank: 143, name: "Moss (Accounting Firm)", hq_city: "Birmingham", hq_state: "AL", website_url: "https://www.mosscpas.com", careers_url: "https://www.mosscpas.com/careers" },
  { rank: 144, name: "Pinaki & Associates", hq_city: "Newark", hq_state: "DE", website_url: "https://www.pinaki.com", careers_url: "https://www.pinaki.com/careers" },
  { rank: 145, name: "Tetrick & Bartlett", hq_city: "Clarksburg", hq_state: "WV", website_url: "https://www.tetrickbartlett.com", careers_url: "https://www.tetrickbartlett.com/careers" },
  { rank: 146, name: "Laporte CPAs & Business Advisors", hq_city: "Metairie", hq_state: "LA", website_url: "https://www.laportecpa.com", careers_url: "https://www.laportecpa.com/careers" },
  { rank: 147, name: "Bourgeois Bennett", hq_city: "Metairie", hq_state: "LA", website_url: "https://www.bbcpas.com", careers_url: "https://www.bbcpas.com/careers" },
  { rank: 148, name: "Calhoun, Thomson & Matza", hq_city: "Atlanta", hq_state: "GA", website_url: "https://www.ctmllp.com", careers_url: "https://www.ctmllp.com/careers" },
  { rank: 149, name: "Rodefer Moss & Co", hq_city: "Knoxville", hq_state: "TN", website_url: "https://www.rodefermoss.com", careers_url: "https://www.rodefermoss.com/careers" },
  { rank: 150, name: "Hawkins Ash CPAs", hq_city: "La Crosse", hq_state: "WI", website_url: "https://www.hawkinsashcpas.com", careers_url: "https://www.hawkinsashcpas.com/careers" },
  // ─── ranks 151–250 ───────────────────────────────────────────────────────────
  { rank: 151, name: "Pease Bell CPAs", hq_city: "Cleveland", hq_state: "OH", website_url: "https://www.peasebell.com", careers_url: "https://www.peasebell.com/careers" },
  { rank: 152, name: "Lutz and Company", hq_city: "Omaha", hq_state: "NE", website_url: "https://www.lutz.us", careers_url: "https://www.lutz.us/careers" },
  { rank: 153, name: "Keegan Linscott & Associates", hq_city: "Tucson", hq_state: "AZ", website_url: "https://www.klaaz.com", careers_url: "https://www.klaaz.com/careers" },
  { rank: 154, name: "Kruggel Lawton CPAs", hq_city: "Elkhart", hq_state: "IN", website_url: "https://www.kruggellawton.com", careers_url: "https://www.kruggellawton.com/careers" },
  { rank: 155, name: "Fulcher Haney CPA Group", hq_city: "Raleigh", hq_state: "NC", website_url: "https://www.fulcherhaney.com", careers_url: "https://www.fulcherhaney.com/careers" },
  { rank: 156, name: "Crist, Jasperson & Weaver", hq_city: "Madison", hq_state: "WI", website_url: "https://www.cjwcpa.com", careers_url: "https://www.cjwcpa.com/careers" },
  { rank: 157, name: "Teal Becker & Chiaramonte", hq_city: "Albany", hq_state: "NY", website_url: "https://www.tbccpa.com", careers_url: "https://www.tbccpa.com/careers" },
  { rank: 158, name: "Adams, Brown, Beran & Ball", hq_city: "Great Bend", hq_state: "KS", website_url: "https://www.ab3cpa.com", careers_url: "https://www.ab3cpa.com/careers" },
  { rank: 159, name: "Dixon Hughes Goodman LLP", hq_city: "Charlotte", hq_state: "NC", website_url: "https://www.dhg.com", careers_url: "https://www.dhg.com/careers" },
  { rank: 160, name: "Whitmore, Smith & Thomas", hq_city: "Salt Lake City", hq_state: "UT", website_url: "https://www.wstcpa.com", careers_url: "https://www.wstcpa.com/careers" },
  { rank: 161, name: "Davie Kaplan CPA", hq_city: "Rochester", hq_state: "NY", website_url: "https://www.daviekaplan.com", careers_url: "https://www.daviekaplan.com/careers" },
  { rank: 162, name: "Wipfli CPAs & Consultants", hq_city: "Green Bay", hq_state: "WI", website_url: "https://www.wipfli.com", careers_url: "https://www.wipfli.com/careers" },
  { rank: 163, name: "Lattimore Black Morgan & Cain", hq_city: "Brentwood", hq_state: "TN", website_url: "https://www.lbmc.com", careers_url: "https://www.lbmc.com/careers" },
  { rank: 164, name: "Yount, Hyde & Barbour", hq_city: "Winchester", hq_state: "VA", website_url: "https://www.yhbcpa.com", careers_url: "https://www.yhbcpa.com/careers" },
  { rank: 165, name: "Katz, Nannis + Solomon", hq_city: "Waltham", hq_state: "MA", website_url: "https://www.knspc.com", careers_url: "https://www.knspc.com/careers" },
  { rank: 166, name: "Henry & Horne", hq_city: "Tempe", hq_state: "AZ", website_url: "https://www.hhcpa.com", careers_url: "https://www.hhcpa.com/careers" },
  { rank: 167, name: "Packer Thomas", hq_city: "Youngstown", hq_state: "OH", website_url: "https://www.packerthomas.com", careers_url: "https://www.packerthomas.com/careers" },
  { rank: 168, name: "Erickson, Brown & Kloster", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.ebkcpa.com", careers_url: "https://www.ebkcpa.com/careers" },
  { rank: 169, name: "Porte Brown LLC", hq_city: "Elk Grove Village", hq_state: "IL", website_url: "https://www.portebrown.com", careers_url: "https://www.portebrown.com/careers" },
  { rank: 170, name: "Rogers & Company", hq_city: "Fairfax", hq_state: "VA", website_url: "https://www.rogerscompany.com", careers_url: "https://www.rogerscompany.com/careers" },
  { rank: 171, name: "Bland & Associates", hq_city: "Omaha", hq_state: "NE", website_url: "https://www.blandandassociates.com", careers_url: "https://www.blandandassociates.com/careers" },
  { rank: 172, name: "Hein & Associates", hq_city: "Denver", hq_state: "CO", website_url: "https://www.heincpa.com", careers_url: "https://www.heincpa.com/careers" },
  { rank: 173, name: "Battelle & Battelle", hq_city: "Troy", hq_state: "OH", website_url: "https://www.battelle-cpa.com", careers_url: "https://www.battelle-cpa.com/careers" },
  { rank: 174, name: "Habif, Arogeti & Wynne", hq_city: "Atlanta", hq_state: "GA", website_url: "https://www.hawcpa.com", careers_url: "https://www.hawcpa.com/careers" },
  { rank: 175, name: "Dalby, Wendland & Co.", hq_city: "Grand Junction", hq_state: "CO", website_url: "https://www.dalbywendland.com", careers_url: "https://www.dalbywendland.com/careers" },
  { rank: 176, name: "Ellin & Tucker Chartered", hq_city: "Baltimore", hq_state: "MD", website_url: "https://www.ellintucker.com", careers_url: "https://www.ellintucker.com/careers" },
  { rank: 177, name: "Rivero, Gordimer & Company", hq_city: "Tampa", hq_state: "FL", website_url: "https://www.riverogordimer.com", careers_url: "https://www.riverogordimer.com/careers" },
  { rank: 178, name: "Barfield Murphy Shank & Smith", hq_city: "Birmingham", hq_state: "AL", website_url: "https://www.bmsscpa.com", careers_url: "https://www.bmsscpa.com/careers" },
  { rank: 179, name: "Insero & Co. CPAs", hq_city: "Rochester", hq_state: "NY", website_url: "https://www.inseroco.com", careers_url: "https://www.inseroco.com/careers" },
  { rank: 180, name: "Whitley Penn LLP", hq_city: "Fort Worth", hq_state: "TX", website_url: "https://www.whitleypenn.com", careers_url: "https://www.whitleypenn.com/careers" },
  { rank: 181, name: "Woelfel CPAs", hq_city: "Toledo", hq_state: "OH", website_url: "https://www.woelfelcpas.com", careers_url: "https://www.woelfelcpas.com/careers" },
  { rank: 182, name: "Sussman Shank", hq_city: "Portland", hq_state: "OR", website_url: "https://www.sussmanshank.com", careers_url: "https://www.sussmanshank.com/careers" },
  { rank: 183, name: "Reznick Group", hq_city: "Bethesda", hq_state: "MD", website_url: "https://www.reznickgroup.com", careers_url: "https://www.reznickgroup.com/careers" },
  { rank: 184, name: "Moss, Krusick & Associates", hq_city: "Winter Park", hq_state: "FL", website_url: "https://www.mka-cpa.com", careers_url: "https://www.mka-cpa.com/careers" },
  { rank: 185, name: "Patzner, Rubie & Co.", hq_city: "St. Cloud", hq_state: "MN", website_url: "https://www.patznerrubie.com", careers_url: "https://www.patznerrubie.com/careers" },
  { rank: 186, name: "Croyts, Pierce & Turner", hq_city: "Jackson", hq_state: "MI", website_url: "https://www.cptnm.com", careers_url: "https://www.cptnm.com/careers" },
  { rank: 187, name: "Schellman & Company", hq_city: "Tampa", hq_state: "FL", website_url: "https://www.schellman.com", careers_url: "https://www.schellman.com/careers" },
  { rank: 188, name: "Dent Moses LLP", hq_city: "Birmingham", hq_state: "AL", website_url: "https://www.dentmoses.com", careers_url: "https://www.dentmoses.com/careers" },
  { rank: 189, name: "Wegner CPAs", hq_city: "Madison", hq_state: "WI", website_url: "https://www.wegnercpas.com", careers_url: "https://www.wegnercpas.com/careers" },
  { rank: 190, name: "Hill, Barth & King LLC", hq_city: "Youngstown", hq_state: "OH", website_url: "https://www.hbkcpa.com", careers_url: "https://www.hbkcpa.com/careers" },
  { rank: 191, name: "Rosenfield & Company", hq_city: "New York", hq_state: "NY", website_url: "https://www.rosenfieldco.com", careers_url: "https://www.rosenfieldco.com/careers" },
  { rank: 192, name: "Kraft CPAs", hq_city: "Nashville", hq_state: "TN", website_url: "https://www.kraftcpas.com", careers_url: "https://www.kraftcpas.com/careers" },
  { rank: 193, name: "Anglin Reichmann Armstrong", hq_city: "Huntsville", hq_state: "AL", website_url: "https://www.anglinreichmann.com", careers_url: "https://www.anglinreichmann.com/careers" },
  { rank: 194, name: "Frazier & Deeter CPAs", hq_city: "Atlanta", hq_state: "GA", website_url: "https://www.frazierdeeter.com", careers_url: "https://www.frazierdeeter.com/careers" },
  { rank: 195, name: "Carr, Riggs & Ingram LLC", hq_city: "Pensacola", hq_state: "FL", website_url: "https://www.cricpa.com", careers_url: "https://www.cricpa.com/careers" },
  { rank: 196, name: "Cummings, Keegan & Co.", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.ckcpas.com", careers_url: "https://www.ckcpas.com/careers" },
  { rank: 197, name: "Aldridge Borden & Company", hq_city: "Montgomery", hq_state: "AL", website_url: "https://www.aldridgeborden.com", careers_url: "https://www.aldridgeborden.com/careers" },
  { rank: 198, name: "Swart, Lalande & Associates", hq_city: "Sarasota", hq_state: "FL", website_url: "https://www.swartlalande.com", careers_url: "https://www.swartlalande.com/careers" },
  { rank: 199, name: "Clifton Gunderson", hq_city: "Peoria", hq_state: "IL", website_url: "https://www.cliftoncpa.com", careers_url: "https://www.cliftoncpa.com/careers" },
  { rank: 200, name: "Plante & Moran PLLC", hq_city: "Southfield", hq_state: "MI", website_url: "https://www.plantemoran.com", careers_url: "https://www.plantemoran.com/careers" },
  // ─── ranks 201–300 ───────────────────────────────────────────────────────────
  { rank: 201, name: "BNN (Baker Newman Noyes)", hq_city: "Portland", hq_state: "ME", website_url: "https://www.bnncpa.com", careers_url: "https://www.bnncpa.com/careers" },
  { rank: 202, name: "Seay, Felton & Lowe", hq_city: "Nashville", hq_state: "TN", website_url: "https://www.sflcpa.com", careers_url: "https://www.sflcpa.com/careers" },
  { rank: 203, name: "Kessler Orlean Silver & Co.", hq_city: "Boca Raton", hq_state: "FL", website_url: "https://www.koscpa.com", careers_url: "https://www.koscpa.com/careers" },
  { rank: 204, name: "Fried & Kowgios Partners", hq_city: "New York", hq_state: "NY", website_url: "https://www.fkpcpas.com", careers_url: "https://www.fkpcpas.com/careers" },
  { rank: 205, name: "Lauterbach & Amen", hq_city: "Warrenville", hq_state: "IL", website_url: "https://www.lauterbachamen.com", careers_url: "https://www.lauterbachamen.com/careers" },
  { rank: 206, name: "Belfint, Lyons & Shuman", hq_city: "Wilmington", hq_state: "DE", website_url: "https://www.belfint.com", careers_url: "https://www.belfint.com/careers" },
  { rank: 207, name: "Boeckermann Grafstrom & Mayer", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.bgmcpa.com", careers_url: "https://www.bgmcpa.com/careers" },
  { rank: 208, name: "Cassell & Associates", hq_city: "Louisville", hq_state: "KY", website_url: "https://www.cassellcpa.com", careers_url: "https://www.cassellcpa.com/careers" },
  { rank: 209, name: "Coulter & Justus PC", hq_city: "Knoxville", hq_state: "TN", website_url: "https://www.cjpc.com", careers_url: "https://www.cjpc.com/careers" },
  { rank: 210, name: "Davie Kaplan CPAs", hq_city: "Rochester", hq_state: "NY", website_url: "https://www.daviekaplan.com", careers_url: "https://www.daviekaplan.com/careers" },
  { rank: 211, name: "DeLeon & Stang", hq_city: "Gaithersburg", hq_state: "MD", website_url: "https://www.deleonandstang.com", careers_url: "https://www.deleonandstang.com/careers" },
  { rank: 212, name: "Dennard, Lascar Associates", hq_city: "Memphis", hq_state: "TN", website_url: "https://www.dlacpa.com", careers_url: "https://www.dlacpa.com/careers" },
  { rank: 213, name: "Dohan & Company", hq_city: "Miami", hq_state: "FL", website_url: "https://www.dohancpa.com", careers_url: "https://www.dohancpa.com/careers" },
  { rank: 214, name: "Duplantier, Hrapmann, Hogan & Maher", hq_city: "New Orleans", hq_state: "LA", website_url: "https://www.dhhm.com", careers_url: "https://www.dhhm.com/careers" },
  { rank: 215, name: "Eisner Advisory Group", hq_city: "New York", hq_state: "NY", website_url: "https://www.eisneradvisory.com", careers_url: "https://www.eisneradvisory.com/careers" },
  { rank: 216, name: "Farrow-Gillespie Heath Witter", hq_city: "Dallas", hq_state: "TX", website_url: "https://www.fghwcpa.com", careers_url: "https://www.fghwcpa.com/careers" },
  { rank: 217, name: "Fenton & Church CPAs", hq_city: "Spokane", hq_state: "WA", website_url: "https://www.fentonchurch.com", careers_url: "https://www.fentonchurch.com/careers" },
  { rank: 218, name: "Frazer, LLP", hq_city: "Garden City", hq_state: "NY", website_url: "https://www.frazercpa.com", careers_url: "https://www.frazercpa.com/careers" },
  { rank: 219, name: "Geffen Mesher & Company", hq_city: "Portland", hq_state: "OR", website_url: "https://www.geffenmesher.com", careers_url: "https://www.geffenmesher.com/careers" },
  { rank: 220, name: "Gold Mantello & Brown CPAs", hq_city: "New Bedford", hq_state: "MA", website_url: "https://www.goldmantello.com", careers_url: "https://www.goldmantello.com/careers" },
  { rank: 221, name: "Gomerdinger & Associates", hq_city: "Phoenix", hq_state: "AZ", website_url: "https://www.gomerdinger.com", careers_url: "https://www.gomerdinger.com/careers" },
  { rank: 222, name: "Gray, Griffith & Mays", hq_city: "Charleston", hq_state: "WV", website_url: "https://www.ggmcpa.com", careers_url: "https://www.ggmcpa.com/careers" },
  { rank: 223, name: "Grossman Yanak & Ford LLP", hq_city: "Pittsburgh", hq_state: "PA", website_url: "https://www.gyf.com", careers_url: "https://www.gyf.com/careers" },
  { rank: 224, name: "Haefele Flanagan & Co.", hq_city: "Moorestown", hq_state: "NJ", website_url: "https://www.hfcco.com", careers_url: "https://www.hfcco.com/careers" },
  { rank: 225, name: "Hansen, Barnett & Maxwell", hq_city: "Salt Lake City", hq_state: "UT", website_url: "https://www.hbmcpa.com", careers_url: "https://www.hbmcpa.com/careers" },
  { rank: 226, name: "Harper & Pearson Company", hq_city: "Houston", hq_state: "TX", website_url: "https://www.harperpearson.com", careers_url: "https://www.harperpearson.com/careers" },
  { rank: 227, name: "Harris & Harris Ltd.", hq_city: "Chicago", hq_state: "IL", website_url: "https://www.harrisharris.com", careers_url: "https://www.harrisharris.com/careers" },
  { rank: 228, name: "Hermanson & Company LLP", hq_city: "Seattle", hq_state: "WA", website_url: "https://www.hermanson.com", careers_url: "https://www.hermanson.com/careers" },
  { rank: 229, name: "Herr, Potts & Potts", hq_city: "Lancaster", hq_state: "PA", website_url: "https://www.herrpotts.com", careers_url: "https://www.herrpotts.com/careers" },
  { rank: 230, name: "Hinton Burdick", hq_city: "St. George", hq_state: "UT", website_url: "https://www.hintonburdick.com", careers_url: "https://www.hintonburdick.com/careers" },
  { rank: 231, name: "Hood & Strong LLP", hq_city: "San Francisco", hq_state: "CA", website_url: "https://www.hoodstrong.com", careers_url: "https://www.hoodstrong.com/careers" },
  { rank: 232, name: "Hughes, Pittman & Gupton", hq_city: "Raleigh", hq_state: "NC", website_url: "https://www.hpgcpa.com", careers_url: "https://www.hpgcpa.com/careers" },
  { rank: 233, name: "Hurst, Moore & Park", hq_city: "Florence", hq_state: "SC", website_url: "https://www.hurstmoore.com", careers_url: "https://www.hurstmoore.com/careers" },
  { rank: 234, name: "Irsfeld, Irsfeld & Younger LLP", hq_city: "San Fernando", hq_state: "CA", website_url: "https://www.iiygroup.com", careers_url: "https://www.iiygroup.com/careers" },
  { rank: 235, name: "J.H. Cohn LLP", hq_city: "Roseland", hq_state: "NJ", website_url: "https://www.jhcohn.com", careers_url: "https://www.jhcohn.com/careers" },
  { rank: 236, name: "Jaeckle, Fleischmann & Mugel", hq_city: "Buffalo", hq_state: "NY", website_url: "https://www.jaeckle.com", careers_url: "https://www.jaeckle.com/careers" },
  { rank: 237, name: "James, Hardy & Haley", hq_city: "Mobile", hq_state: "AL", website_url: "https://www.jhh-cpas.com", careers_url: "https://www.jhh-cpas.com/careers" },
  { rank: 238, name: "Johnson Price Sprinkle PA", hq_city: "Asheville", hq_state: "NC", website_url: "https://www.jpscpa.com", careers_url: "https://www.jpscpa.com/careers" },
  { rank: 239, name: "Jones, Nale & Mattingly", hq_city: "Louisville", hq_state: "KY", website_url: "https://www.jnmcpa.com", careers_url: "https://www.jnmcpa.com/careers" },
  { rank: 240, name: "Kanter, Teiger, Vance & Zimmerman", hq_city: "Parsippany", hq_state: "NJ", website_url: "https://www.ktvz.com", careers_url: "https://www.ktvz.com/careers" },
  { rank: 241, name: "Keiter", hq_city: "Richmond", hq_state: "VA", website_url: "https://www.keitercpa.com", careers_url: "https://www.keitercpa.com/careers" },
  { rank: 242, name: "Kerber, Eck & Braeckel LLP", hq_city: "Springfield", hq_state: "IL", website_url: "https://www.keb.com", careers_url: "https://www.keb.com/careers" },
  { rank: 243, name: "Kforce Inc", hq_city: "Tampa", hq_state: "FL", website_url: "https://www.kforce.com", careers_url: "https://www.kforce.com/careers" },
  { rank: 244, name: "Kirwan, Nahorney & Associates", hq_city: "Moorestown", hq_state: "NJ", website_url: "https://www.knacpas.com", careers_url: "https://www.knacpas.com/careers" },
  { rank: 245, name: "Kite, Shields & Webb", hq_city: "Memphis", hq_state: "TN", website_url: "https://www.kswcpa.com", careers_url: "https://www.kswcpa.com/careers" },
  { rank: 246, name: "Knapp & Associates", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.knappcpa.com", careers_url: "https://www.knappcpa.com/careers" },
  { rank: 247, name: "Knight CPAs", hq_city: "Indianapolis", hq_state: "IN", website_url: "https://www.knightcpas.com", careers_url: "https://www.knightcpas.com/careers" },
  { rank: 248, name: "LBMC PC", hq_city: "Brentwood", hq_state: "TN", website_url: "https://www.lbmc.com", careers_url: "https://www.lbmc.com/careers" },
  { rank: 249, name: "Leaf & Cole LLP", hq_city: "San Diego", hq_state: "CA", website_url: "https://www.leafandcole.com", careers_url: "https://www.leafandcole.com/careers" },
  { rank: 250, name: "Lester, Dodge & Smith", hq_city: "Milwaukee", hq_state: "WI", website_url: "https://www.ldsllp.com", careers_url: "https://www.ldsllp.com/careers" },
  // ─── ranks 251–350 ───────────────────────────────────────────────────────────
  { rank: 251, name: "Lewis, Birch & Ricardo", hq_city: "Miami", hq_state: "FL", website_url: "https://www.lbrcpa.com", careers_url: "https://www.lbrcpa.com/careers" },
  { rank: 252, name: "Linkenheimer LLP", hq_city: "Santa Rosa", hq_state: "CA", website_url: "https://www.linkenheimer.com", careers_url: "https://www.linkenheimer.com/careers" },
  { rank: 253, name: "Loring, Ward & Associates", hq_city: "San Jose", hq_state: "CA", website_url: "https://www.loringward.com", careers_url: "https://www.loringward.com/careers" },
  { rank: 254, name: "Lowenhaupt Global Advisors", hq_city: "St. Louis", hq_state: "MO", website_url: "https://www.lowenhaupt.com", careers_url: "https://www.lowenhaupt.com/careers" },
  { rank: 255, name: "Luby, Beamesderfer & Associates", hq_city: "Hagerstown", hq_state: "MD", website_url: "https://www.lubycpa.com", careers_url: "https://www.lubycpa.com/careers" },
  { rank: 256, name: "Lunt & Associates", hq_city: "Phoenix", hq_state: "AZ", website_url: "https://www.luntcpa.com", careers_url: "https://www.luntcpa.com/careers" },
  { rank: 257, name: "Lynch, Cox, Gilman & Goodman", hq_city: "Louisville", hq_state: "KY", website_url: "https://www.lcggcpa.com", careers_url: "https://www.lcggcpa.com/careers" },
  { rank: 258, name: "Mahon, Mahon, Kerins & Company", hq_city: "Philadelphia", hq_state: "PA", website_url: "https://www.mmkc.com", careers_url: "https://www.mmkc.com/careers" },
  { rank: 259, name: "Marks Nelson LLC", hq_city: "Kansas City", hq_state: "MO", website_url: "https://www.marksnelson.com", careers_url: "https://www.marksnelson.com/careers" },
  { rank: 260, name: "Markovitz, Starkman & Brand", hq_city: "Boca Raton", hq_state: "FL", website_url: "https://www.msbcpa.com", careers_url: "https://www.msbcpa.com/careers" },
  { rank: 261, name: "Martin & Gieseking", hq_city: "Quincy", hq_state: "IL", website_url: "https://www.mggcpa.com", careers_url: "https://www.mggcpa.com/careers" },
  { rank: 262, name: "McSoley McCoy & Co", hq_city: "Burlington", hq_state: "VT", website_url: "https://www.mcsoley-mccoy.com", careers_url: "https://www.mcsoley-mccoy.com/careers" },
  { rank: 263, name: "Metz Lewis LLC", hq_city: "Pittsburgh", hq_state: "PA", website_url: "https://www.metzlewis.com", careers_url: "https://www.metzlewis.com/careers" },
  { rank: 264, name: "Mika Meyers PC", hq_city: "Grand Rapids", hq_state: "MI", website_url: "https://www.mikameyers.com", careers_url: "https://www.mikameyers.com/careers" },
  { rank: 265, name: "Miller, Cooper & Co.", hq_city: "Deerfield", hq_state: "IL", website_url: "https://www.millercooper.com", careers_url: "https://www.millercooper.com/careers" },
  { rank: 266, name: "Mitchell Martin Inc", hq_city: "New York", hq_state: "NY", website_url: "https://www.mitchellmartin.com", careers_url: "https://www.mitchellmartin.com/careers" },
  { rank: 267, name: "Mixon Hill", hq_city: "Montgomery", hq_state: "AL", website_url: "https://www.mixonhill.com", careers_url: "https://www.mixonhill.com/careers" },
  { rank: 268, name: "Morningstar CPAs", hq_city: "Greensboro", hq_state: "NC", website_url: "https://www.morningstarcpas.com", careers_url: "https://www.morningstarcpas.com/careers" },
  { rank: 269, name: "Mueller Prost CPAs", hq_city: "St. Louis", hq_state: "MO", website_url: "https://www.muellerprost.com", careers_url: "https://www.muellerprost.com/careers" },
  { rank: 270, name: "Murphey & Company", hq_city: "Columbia", hq_state: "MO", website_url: "https://www.murpheyco.com", careers_url: "https://www.murpheyco.com/careers" },
  { rank: 271, name: "Myers and Stauffer LC", hq_city: "Topeka", hq_state: "KS", website_url: "https://www.myersandstauffer.com", careers_url: "https://www.myersandstauffer.com/careers" },
  { rank: 272, name: "Newlan & Newlan", hq_city: "Colorado Springs", hq_state: "CO", website_url: "https://www.newlancpa.com", careers_url: "https://www.newlancpa.com/careers" },
  { rank: 273, name: "Nicholas, Cauley & Associates", hq_city: "Augusta", hq_state: "GA", website_url: "https://www.nicholascauley.com", careers_url: "https://www.nicholascauley.com/careers" },
  { rank: 274, name: "Nussbaum Berg & Campbell", hq_city: "Providence", hq_state: "RI", website_url: "https://www.nbccpa.com", careers_url: "https://www.nbccpa.com/careers" },
  { rank: 275, name: "O'Connor & Drew PC", hq_city: "Braintree", hq_state: "MA", website_url: "https://www.oconnorandrew.com", careers_url: "https://www.oconnorandrew.com/careers" },
  { rank: 276, name: "Orcutt & Company", hq_city: "Columbus", hq_state: "OH", website_url: "https://www.orcuttcpa.com", careers_url: "https://www.orcuttcpa.com/careers" },
  { rank: 277, name: "Pagel Davis & Hill PC", hq_city: "Houston", hq_state: "TX", website_url: "https://www.pdhtx.com", careers_url: "https://www.pdhtx.com/careers" },
  { rank: 278, name: "Panell Kerr Foster", hq_city: "Boston", hq_state: "MA", website_url: "https://www.pkf.com", careers_url: "https://www.pkf.com/careers" },
  { rank: 279, name: "Patterson Flynn & Martin", hq_city: "Oakland", hq_state: "CA", website_url: "https://www.pfmcpa.com", careers_url: "https://www.pfmcpa.com/careers" },
  { rank: 280, name: "Pearce, Bevill, Leesburg, Moore", hq_city: "Birmingham", hq_state: "AL", website_url: "https://www.pblmcpa.com", careers_url: "https://www.pblmcpa.com/careers" },
  { rank: 281, name: "Perkins & Company", hq_city: "Portland", hq_state: "OR", website_url: "https://www.perkins-cpas.com", careers_url: "https://www.perkins-cpas.com/careers" },
  { rank: 282, name: "Pestine, Sherr & Gold", hq_city: "Baltimore", hq_state: "MD", website_url: "https://www.psgcpa.com", careers_url: "https://www.psgcpa.com/careers" },
  { rank: 283, name: "Plattner, Schneidman & Associates", hq_city: "Los Angeles", hq_state: "CA", website_url: "https://www.pscpa.com", careers_url: "https://www.pscpa.com/careers" },
  { rank: 284, name: "Price, Brent & Company", hq_city: "San Antonio", hq_state: "TX", website_url: "https://www.pricebrent.com", careers_url: "https://www.pricebrent.com/careers" },
  { rank: 285, name: "Pringle & Herigstad", hq_city: "Minot", hq_state: "ND", website_url: "https://www.phcpas.com", careers_url: "https://www.phcpas.com/careers" },
  { rank: 286, name: "Purk & Associates", hq_city: "St. Louis", hq_state: "MO", website_url: "https://www.purkassociates.com", careers_url: "https://www.purkassociates.com/careers" },
  { rank: 287, name: "Raffa PC", hq_city: "Washington", hq_state: "DC", website_url: "https://www.raffa.com", careers_url: "https://www.raffa.com/careers" },
  { rank: 288, name: "Rehmann Robson CPAs", hq_city: "Troy", hq_state: "MI", website_url: "https://www.rehmann.com", careers_url: "https://www.rehmann.com/careers" },
  { rank: 289, name: "Reilly, Penner & Benton LLP", hq_city: "Milwaukee", hq_state: "WI", website_url: "https://www.rpb.com", careers_url: "https://www.rpb.com/careers" },
  { rank: 290, name: "Renner & Company", hq_city: "Alexandria", hq_state: "VA", website_url: "https://www.rennercpa.com", careers_url: "https://www.rennercpa.com/careers" },
  { rank: 291, name: "Ringmaster Technologies", hq_city: "Middleburg Heights", hq_state: "OH", website_url: "https://www.ringmaster.com", careers_url: "https://www.ringmaster.com/careers" },
  { rank: 292, name: "Robinson, Farmer, Cox Associates", hq_city: "Lynchburg", hq_state: "VA", website_url: "https://www.rfcva.com", careers_url: "https://www.rfcva.com/careers" },
  { rank: 293, name: "Rodman CPAs", hq_city: "Waltham", hq_state: "MA", website_url: "https://www.rodmancpa.com", careers_url: "https://www.rodmancpa.com/careers" },
  { rank: 294, name: "Rosenberg, Rich Baker Berman & Co.", hq_city: "Bridgewater", hq_state: "NJ", website_url: "https://www.rrbb.com", careers_url: "https://www.rrbb.com/careers" },
  { rank: 295, name: "Roth & Company PC", hq_city: "Des Moines", hq_state: "IA", website_url: "https://www.rothcpa.com", careers_url: "https://www.rothcpa.com/careers" },
  { rank: 296, name: "Rubin & Rudman LLP", hq_city: "Boston", hq_state: "MA", website_url: "https://www.rubinrudman.com", careers_url: "https://www.rubinrudman.com/careers" },
  { rank: 297, name: "Rudler, PSC", hq_city: "Covington", hq_state: "KY", website_url: "https://www.rudler.com", careers_url: "https://www.rudler.com/careers" },
  { rank: 298, name: "Runyon Kersteen Ouellette CPAs", hq_city: "South Portland", hq_state: "ME", website_url: "https://www.rkocpas.com", careers_url: "https://www.rkocpas.com/careers" },
  { rank: 299, name: "S.R. Snodgrass PC", hq_city: "Wexford", hq_state: "PA", website_url: "https://www.srsnodgrass.com", careers_url: "https://www.srsnodgrass.com/careers" },
  { rank: 300, name: "Salter Labs (Not CPA - skip)", hq_city: "Arvin", hq_state: "CA", website_url: "https://www.salterlabs.com", careers_url: "https://www.salterlabs.com/careers" },
  // ─── ranks 301–400 ───────────────────────────────────────────────────────────
  { rank: 301, name: "Schechter Dokken Kanter", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.sdkcpa.com", careers_url: "https://www.sdkcpa.com/careers" },
  { rank: 302, name: "Seiler LLP", hq_city: "Redwood City", hq_state: "CA", website_url: "https://www.seilerllp.com", careers_url: "https://www.seilerllp.com/careers" },
  { rank: 303, name: "Shannon & Associates", hq_city: "Auburn", hq_state: "WA", website_url: "https://www.shannon-cpas.com", careers_url: "https://www.shannon-cpas.com/careers" },
  { rank: 304, name: "Sipkema & Company", hq_city: "Grand Rapids", hq_state: "MI", website_url: "https://www.sipkemacpa.com", careers_url: "https://www.sipkemacpa.com/careers" },
  { rank: 305, name: "Skoda Minotti", hq_city: "Cleveland", hq_state: "OH", website_url: "https://www.skodam.com", careers_url: "https://www.skodam.com/careers" },
  { rank: 306, name: "Sobon & Rose CPA", hq_city: "Uniontown", hq_state: "PA", website_url: "https://www.sobonrose.com", careers_url: "https://www.sobonrose.com/careers" },
  { rank: 307, name: "Spies, Bell & Associates", hq_city: "Cincinnati", hq_state: "OH", website_url: "https://www.spiesbell.com", careers_url: "https://www.spiesbell.com/careers" },
  { rank: 308, name: "Squar, Milner, Peterson, Miranda & Williamson", hq_city: "Newport Beach", hq_state: "CA", website_url: "https://www.squarmilner.com", careers_url: "https://www.squarmilner.com/careers" },
  { rank: 309, name: "Stark, Winter, Schenkein & Co.", hq_city: "Denver", hq_state: "CO", website_url: "https://www.swscpas.com", careers_url: "https://www.swscpas.com/careers" },
  { rank: 310, name: "Stout CPAs & Advisors", hq_city: "Chicago", hq_state: "IL", website_url: "https://www.stout.com", careers_url: "https://www.stout.com/careers" },
  { rank: 311, name: "Strothman and Company", hq_city: "Louisville", hq_state: "KY", website_url: "https://www.strothman.com", careers_url: "https://www.strothman.com/careers" },
  { rank: 312, name: "Swenson Advisors LLP", hq_city: "Riverside", hq_state: "CA", website_url: "https://www.swensonadvisors.com", careers_url: "https://www.swensonadvisors.com/careers" },
  { rank: 313, name: "Talend Inc.", hq_city: "Redwood City", hq_state: "CA", website_url: "https://www.talend.com", careers_url: "https://www.talend.com/company/careers" },
  { rank: 314, name: "Teal, Becker & Chiaramonte CPAs", hq_city: "Albany", hq_state: "NY", website_url: "https://www.tbccpa.com", careers_url: "https://www.tbccpa.com/careers" },
  { rank: 315, name: "Thomson Reuters Tax & Accounting", hq_city: "Carrollton", hq_state: "TX", website_url: "https://www.tr.com", careers_url: "https://www.tr.com/en/careers" },
  { rank: 316, name: "Tillman & Associates CPAs", hq_city: "Jackson", hq_state: "MS", website_url: "https://www.tillmancpas.com", careers_url: "https://www.tillmancpas.com/careers" },
  { rank: 317, name: "Tippit, Clegg & Turner", hq_city: "Little Rock", hq_state: "AR", website_url: "https://www.tctnow.com", careers_url: "https://www.tctnow.com/careers" },
  { rank: 318, name: "Todd, Weld, Bussert & McClean", hq_city: "Memphis", hq_state: "TN", website_url: "https://www.twbm.com", careers_url: "https://www.twbm.com/careers" },
  { rank: 319, name: "Tonn & Blank CPAs", hq_city: "Michigan City", hq_state: "IN", website_url: "https://www.tonnblank.com", careers_url: "https://www.tonnblank.com/careers" },
  { rank: 320, name: "Tonneson and Company CPAs", hq_city: "Wakefield", hq_state: "MA", website_url: "https://www.tonneson.com", careers_url: "https://www.tonneson.com/careers" },
  { rank: 321, name: "Touche Ross & Co.", hq_city: "New York", hq_state: "NY", website_url: "https://www.deloitte.com", careers_url: "https://www.deloitte.com/us/en/careers.html" },
  { rank: 322, name: "Traphagen Financial Group", hq_city: "Oradell", hq_state: "NJ", website_url: "https://www.traphagen.com", careers_url: "https://www.traphagen.com/careers" },
  { rank: 323, name: "Trout, Ebersole & Groff LLP", hq_city: "Lancaster", hq_state: "PA", website_url: "https://www.teg-cpa.com", careers_url: "https://www.teg-cpa.com/careers" },
  { rank: 324, name: "Tucker, Arensberg & Porter", hq_city: "Pittsburgh", hq_state: "PA", website_url: "https://www.tuckerlaw.com", careers_url: "https://www.tuckerlaw.com/careers" },
  { rank: 325, name: "Ulrich and Associates", hq_city: "Wichita", hq_state: "KS", website_url: "https://www.ulrichcpa.com", careers_url: "https://www.ulrichcpa.com/careers" },
  { rank: 326, name: "Urish Popeck & Co.", hq_city: "Pittsburgh", hq_state: "PA", website_url: "https://www.urishpopeck.com", careers_url: "https://www.urishpopeck.com/careers" },
  { rank: 327, name: "Utley, Hadley & Hadley", hq_city: "Tulsa", hq_state: "OK", website_url: "https://www.uhhcpa.com", careers_url: "https://www.uhhcpa.com/careers" },
  { rank: 328, name: "Vanderburg & Johnson", hq_city: "Nashville", hq_state: "TN", website_url: "https://www.vanderburgcpa.com", careers_url: "https://www.vanderburgcpa.com/careers" },
  { rank: 329, name: "Varney & Associates CPAs", hq_city: "Traverse City", hq_state: "MI", website_url: "https://www.varneyassociates.com", careers_url: "https://www.varneyassociates.com/careers" },
  { rank: 330, name: "Verdure Sciences", hq_city: "Loveland", hq_state: "CO", website_url: "https://www.verdure-sciences.com", careers_url: "https://www.verdure-sciences.com/careers" },
  { rank: 331, name: "Virchow Krause & Company", hq_city: "Madison", hq_state: "WI", website_url: "https://www.virchowkrause.com", careers_url: "https://www.virchowkrause.com/careers" },
  { rank: 332, name: "Vollmer Associates LLP", hq_city: "New York", hq_state: "NY", website_url: "https://www.vollmerassociates.com", careers_url: "https://www.vollmerassociates.com/careers" },
  { rank: 333, name: "W.T. Uniack & Co.", hq_city: "Atlanta", hq_state: "GA", website_url: "https://www.wtuniack.com", careers_url: "https://www.wtuniack.com/careers" },
  { rank: 334, name: "Walters & Helm CPAs", hq_city: "Tulsa", hq_state: "OK", website_url: "https://www.waltershelm.com", careers_url: "https://www.waltershelm.com/careers" },
  { rank: 335, name: "Waylander Consulting Group", hq_city: "Chicago", hq_state: "IL", website_url: "https://www.waylander.com", careers_url: "https://www.waylander.com/careers" },
  { rank: 336, name: "Weinstein, Anastasio & Associates", hq_city: "New Haven", hq_state: "CT", website_url: "https://www.waacpa.com", careers_url: "https://www.waacpa.com/careers" },
  { rank: 337, name: "Weld Evans Croteau & Co.", hq_city: "Concord", hq_state: "NH", website_url: "https://www.wecdcpa.com", careers_url: "https://www.wecdcpa.com/careers" },
  { rank: 338, name: "Wells, Coleman & Associates", hq_city: "Richmond", hq_state: "VA", website_url: "https://www.wellscoleman.com", careers_url: "https://www.wellscoleman.com/careers" },
  { rank: 339, name: "Wertz & Wertz CPAs", hq_city: "Dayton", hq_state: "OH", website_url: "https://www.wertzcpas.com", careers_url: "https://www.wertzcpas.com/careers" },
  { rank: 340, name: "Wessels Arnold & Henderson", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.wahcpa.com", careers_url: "https://www.wahcpa.com/careers" },
  { rank: 341, name: "West & Juhl CPAs", hq_city: "Aberdeen", hq_state: "SD", website_url: "https://www.westjuhl.com", careers_url: "https://www.westjuhl.com/careers" },
  { rank: 342, name: "Wicke Reyn & Associates", hq_city: "Cincinnati", hq_state: "OH", website_url: "https://www.wickereyn.com", careers_url: "https://www.wickereyn.com/careers" },
  { rank: 343, name: "Wiss & Company LLP", hq_city: "Florham Park", hq_state: "NJ", website_url: "https://www.wiss.com", careers_url: "https://www.wiss.com/careers" },
  { rank: 344, name: "Wolf & Company PC", hq_city: "Boston", hq_state: "MA", website_url: "https://www.wolfandco.com", careers_url: "https://www.wolfandco.com/careers" },
  { rank: 345, name: "Wolpoff & Company", hq_city: "Bethesda", hq_state: "MD", website_url: "https://www.wolpoffco.com", careers_url: "https://www.wolpoffco.com/careers" },
  { rank: 346, name: "Wotring, Dyer & Rowe CPAs", hq_city: "Columbus", hq_state: "OH", website_url: "https://www.wdrcpa.com", careers_url: "https://www.wdrcpa.com/careers" },
  { rank: 347, name: "Wright Ford Young & Co.", hq_city: "Irvine", hq_state: "CA", website_url: "https://www.wfycpa.com", careers_url: "https://www.wfycpa.com/careers" },
  { rank: 348, name: "Yerlan & Associates CPAs", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.yerlancpa.com", careers_url: "https://www.yerlancpa.com/careers" },
  { rank: 349, name: "Young, Hyde & Barbour", hq_city: "Charlottesville", hq_state: "VA", website_url: "https://www.yhbcpa.com", careers_url: "https://www.yhbcpa.com/careers" },
  { rank: 350, name: "Zinner & Co. LLP", hq_city: "Cleveland", hq_state: "OH", website_url: "https://www.zinnerco.com", careers_url: "https://www.zinnerco.com/careers" },
  // ─── ranks 351–500 ───────────────────────────────────────────────────────────
  { rank: 351, name: "Cary, Bautista & Lardner", hq_city: "Milwaukee", hq_state: "WI", website_url: "https://www.cblcpa.com", careers_url: "https://www.cblcpa.com/careers" },
  { rank: 352, name: "Caldwell, Becker, Dervin, Petrick & Co.", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.cbdpcpa.com", careers_url: "https://www.cbdpcpa.com/careers" },
  { rank: 353, name: "Campbell, Rappold & Yurasits LLP", hq_city: "Allentown", hq_state: "PA", website_url: "https://www.crycpa.com", careers_url: "https://www.crycpa.com/careers" },
  { rank: 354, name: "Capin Crouse LLP", hq_city: "Indianapolis", hq_state: "IN", website_url: "https://www.capincrouse.com", careers_url: "https://www.capincrouse.com/careers" },
  { rank: 355, name: "Carboni, Iron & Company CPAs", hq_city: "Saginaw", hq_state: "MI", website_url: "https://www.cicpas.com", careers_url: "https://www.cicpas.com/careers" },
  { rank: 356, name: "Caron & Bletzer PLLC", hq_city: "Kingston", hq_state: "NH", website_url: "https://www.caronbletzer.com", careers_url: "https://www.caronbletzer.com/careers" },
  { rank: 357, name: "Castagra Products Inc.", hq_city: "Reno", hq_state: "NV", website_url: "https://www.castagra.com", careers_url: "https://www.castagra.com/careers" },
  { rank: 358, name: "Cavitch, Familo & Durkin", hq_city: "Cleveland", hq_state: "OH", website_url: "https://www.cavitch.com", careers_url: "https://www.cavitch.com/careers" },
  { rank: 359, name: "Centri Business Consulting", hq_city: "Philadelphia", hq_state: "PA", website_url: "https://www.centriconsulting.com", careers_url: "https://www.centriconsulting.com/careers" },
  { rank: 360, name: "Cerini & Associates LLP", hq_city: "Bohemia", hq_state: "NY", website_url: "https://www.ceriniandassociates.com", careers_url: "https://www.ceriniandassociates.com/careers" },
  { rank: 361, name: "Chesapeake Tax Consultants", hq_city: "Lutherville", hq_state: "MD", website_url: "https://www.chesapeaketax.com", careers_url: "https://www.chesapeaketax.com/careers" },
  { rank: 362, name: "Chugh CPAs & Advisors", hq_city: "Milpitas", hq_state: "CA", website_url: "https://www.chugh.com", careers_url: "https://www.chugh.com/careers" },
  { rank: 363, name: "Clark Schaefer Hackett", hq_city: "Columbus", hq_state: "OH", website_url: "https://www.cshco.com", careers_url: "https://www.cshco.com/careers" },
  { rank: 364, name: "Clifton Larson Allen LLP", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.claconnect.com", careers_url: "https://www.claconnect.com/careers" },
  { rank: 365, name: "Cloud Cavanaugh & Co.", hq_city: "Nashville", hq_state: "TN", website_url: "https://www.cloudcavanaugh.com", careers_url: "https://www.cloudcavanaugh.com/careers" },
  { rank: 366, name: "Cohn Reznick LLP", hq_city: "New York", hq_state: "NY", website_url: "https://www.cohnreznick.com", careers_url: "https://www.cohnreznick.com/careers" },
  { rank: 367, name: "Colliers International Group", hq_city: "Toronto", hq_state: "IL", website_url: "https://www.colliers.com", careers_url: "https://www.colliers.com/en-us/careers" },
  { rank: 368, name: "Combined Professional Services", hq_city: "Baltimore", hq_state: "MD", website_url: "https://www.cpscpa.com", careers_url: "https://www.cpscpa.com/careers" },
  { rank: 369, name: "Connor Group", hq_city: "Dayton", hq_state: "OH", website_url: "https://www.connorgroup.com", careers_url: "https://www.connorgroup.com/careers" },
  { rank: 370, name: "Cook & Bieler LP", hq_city: "Wayne", hq_state: "PA", website_url: "https://www.cookbieler.com", careers_url: "https://www.cookbieler.com/careers" },
  { rank: 371, name: "Corbin & Company", hq_city: "Riverside", hq_state: "CA", website_url: "https://www.corbincpa.com", careers_url: "https://www.corbincpa.com/careers" },
  { rank: 372, name: "Cornick, Garber & Sandler LLP", hq_city: "New York", hq_state: "NY", website_url: "https://www.cgscpa.com", careers_url: "https://www.cgscpa.com/careers" },
  { rank: 373, name: "Coscia Moos LLC", hq_city: "Chicago", hq_state: "IL", website_url: "https://www.cosciamoosllc.com", careers_url: "https://www.cosciamoosllc.com/careers" },
  { rank: 374, name: "Covington & Burling LLP", hq_city: "Washington", hq_state: "DC", website_url: "https://www.cov.com", careers_url: "https://www.cov.com/en/careers" },
  { rank: 375, name: "Cramer & Associates", hq_city: "Westerville", hq_state: "OH", website_url: "https://www.cramerassociates.com", careers_url: "https://www.cramerassociates.com/careers" },
  { rank: 376, name: "Crawford & Associates PC", hq_city: "Oklahoma City", hq_state: "OK", website_url: "https://www.crawfordcpas.com", careers_url: "https://www.crawfordcpas.com/careers" },
  { rank: 377, name: "Crifasi & Feierstein CPAs", hq_city: "Providence", hq_state: "RI", website_url: "https://www.cfcpas.com", careers_url: "https://www.cfcpas.com/careers" },
  { rank: 378, name: "Cross, Fernandez & Riley LLP", hq_city: "Orlando", hq_state: "FL", website_url: "https://www.cfrcpa.com", careers_url: "https://www.cfrcpa.com/careers" },
  { rank: 379, name: "Culbertson, Bankers, Fink & Associates", hq_city: "Columbus", hq_state: "OH", website_url: "https://www.cbfacpa.com", careers_url: "https://www.cbfacpa.com/careers" },
  { rank: 380, name: "Cultrera, Specter & Cabrera CPAs", hq_city: "Coral Gables", hq_state: "FL", website_url: "https://www.csccpa.com", careers_url: "https://www.csccpa.com/careers" },
  { rank: 381, name: "Cunningham, Vogel & Rost", hq_city: "St. Louis", hq_state: "MO", website_url: "https://www.cvrcpa.com", careers_url: "https://www.cvrcpa.com/careers" },
  { rank: 382, name: "D&H CPA Group", hq_city: "Phoenix", hq_state: "AZ", website_url: "https://www.dhcpagroup.com", careers_url: "https://www.dhcpagroup.com/careers" },
  { rank: 383, name: "Dalby, Wendland & Co. CPAs", hq_city: "Grand Junction", hq_state: "CO", website_url: "https://www.dalbywendland.com", careers_url: "https://www.dalbywendland.com/careers" },
  { rank: 384, name: "Damitz, Brooks, Nightingale & Turner", hq_city: "Santa Barbara", hq_state: "CA", website_url: "https://www.dbntr.com", careers_url: "https://www.dbntr.com/careers" },
  { rank: 385, name: "Darby & Associates", hq_city: "Westborough", hq_state: "MA", website_url: "https://www.darbycpa.com", careers_url: "https://www.darbycpa.com/careers" },
  { rank: 386, name: "Davis & Hodgdon Associates", hq_city: "Williston", hq_state: "VT", website_url: "https://www.davishodgdon.com", careers_url: "https://www.davishodgdon.com/careers" },
  { rank: 387, name: "Dean Witter Reynolds", hq_city: "New York", hq_state: "NY", website_url: "https://www.morganstanley.com", careers_url: "https://www.morganstanley.com/people/careers" },
  { rank: 388, name: "Decosimo CPAs & Business Advisors", hq_city: "Chattanooga", hq_state: "TN", website_url: "https://www.decosimo.com", careers_url: "https://www.decosimo.com/careers" },
  { rank: 389, name: "Dent Moses LLP CPAs", hq_city: "Birmingham", hq_state: "AL", website_url: "https://www.dentmoses.com", careers_url: "https://www.dentmoses.com/careers" },
  { rank: 390, name: "Devaney & Associates", hq_city: "Anchorage", hq_state: "AK", website_url: "https://www.devaneyassociates.com", careers_url: "https://www.devaneyassociates.com/careers" },
  { rank: 391, name: "Dixon & Company", hq_city: "Southfield", hq_state: "MI", website_url: "https://www.dixonco.com", careers_url: "https://www.dixonco.com/careers" },
  { rank: 392, name: "Draffin & Tucker LLP", hq_city: "Albany", hq_state: "GA", website_url: "https://www.draffin-tucker.com", careers_url: "https://www.draffin-tucker.com/careers" },
  { rank: 393, name: "Drees & Schipper", hq_city: "Grand Rapids", hq_state: "MI", website_url: "https://www.dreesschipper.com", careers_url: "https://www.dreesschipper.com/careers" },
  { rank: 394, name: "Drucker & Scaccetti", hq_city: "Philadelphia", hq_state: "PA", website_url: "https://www.dspcpa.com", careers_url: "https://www.dspcpa.com/careers" },
  { rank: 395, name: "Duff & Phelps", hq_city: "Chicago", hq_state: "IL", website_url: "https://www.duffandphelps.com", careers_url: "https://www.duffandphelps.com/careers" },
  { rank: 396, name: "Dunbar, Breitweiser & Company", hq_city: "Kankakee", hq_state: "IL", website_url: "https://www.dunbarbreitweiser.com", careers_url: "https://www.dunbarbreitweiser.com/careers" },
  { rank: 397, name: "Duncan & Duncan CPAs", hq_city: "Spokane", hq_state: "WA", website_url: "https://www.duncancpas.com", careers_url: "https://www.duncancpas.com/careers" },
  { rank: 398, name: "Dunn & Black PS", hq_city: "Spokane", hq_state: "WA", website_url: "https://www.dunnblack.com", careers_url: "https://www.dunnblack.com/careers" },
  { rank: 399, name: "Durkin & Feld CPAs", hq_city: "New York", hq_state: "NY", website_url: "https://www.durkinfeld.com", careers_url: "https://www.durkinfeld.com/careers" },
  { rank: 400, name: "Dwyer Pemberton & Coulson", hq_city: "Tacoma", hq_state: "WA", website_url: "https://www.dpccpa.com", careers_url: "https://www.dpccpa.com/careers" },
  // ─── additional notable firms ─────────────────────────────────────────────
  { rank: 401, name: "Easterday, Dally, Doering & Evans", hq_city: "Columbus", hq_state: "OH", website_url: "https://www.eddecpa.com", careers_url: "https://www.eddecpa.com/careers" },
  { rank: 402, name: "EisnerAmper LLP", hq_city: "New York", hq_state: "NY", website_url: "https://www.eisneramper.com", careers_url: "https://www.eisneramper.com/careers" },
  { rank: 403, name: "Elliott, Robinson & Company", hq_city: "Anchorage", hq_state: "AK", website_url: "https://www.ercak.com", careers_url: "https://www.ercak.com/careers" },
  { rank: 404, name: "Emper, Woomer & Lontos", hq_city: "Philadelphia", hq_state: "PA", website_url: "https://www.ewlcpa.com", careers_url: "https://www.ewlcpa.com/careers" },
  { rank: 405, name: "Erickson & Sederstrom", hq_city: "Omaha", hq_state: "NE", website_url: "https://www.eslaw.com", careers_url: "https://www.eslaw.com/careers" },
  { rank: 406, name: "Ernst & Young LLP", hq_city: "New York", hq_state: "NY", website_url: "https://www.ey.com", careers_url: "https://www.ey.com/en_us/careers" },
  { rank: 407, name: "Esposito & Whitney CPAs", hq_city: "Leominster", hq_state: "MA", website_url: "https://www.ewcpa.com", careers_url: "https://www.ewcpa.com/careers" },
  { rank: 408, name: "Evans, Dodd & Johnson", hq_city: "Tyler", hq_state: "TX", website_url: "https://www.edjcpa.com", careers_url: "https://www.edjcpa.com/careers" },
  { rank: 409, name: "Faherty & Faherty", hq_city: "New York", hq_state: "NY", website_url: "https://www.fahertycpa.com", careers_url: "https://www.fahertycpa.com/careers" },
  { rank: 410, name: "Falvey, Donahue & Tobin", hq_city: "Boston", hq_state: "MA", website_url: "https://www.fdtcpa.com", careers_url: "https://www.fdtcpa.com/careers" },
  { rank: 411, name: "Famularo & Associates", hq_city: "Cherry Hill", hq_state: "NJ", website_url: "https://www.famularocpa.com", careers_url: "https://www.famularocpa.com/careers" },
  { rank: 412, name: "Farris Bobango PLC", hq_city: "Memphis", hq_state: "TN", website_url: "https://www.farrisbobango.com", careers_url: "https://www.farrisbobango.com/careers" },
  { rank: 413, name: "Faulkner & Associates", hq_city: "Boulder", hq_state: "CO", website_url: "https://www.faulknercpa.com", careers_url: "https://www.faulknercpa.com/careers" },
  { rank: 414, name: "Feeley & Driscoll PC", hq_city: "Boston", hq_state: "MA", website_url: "https://www.fdcpa.com", careers_url: "https://www.fdcpa.com/careers" },
  { rank: 415, name: "Ferguson & Jennings CPAs", hq_city: "Greensboro", hq_state: "NC", website_url: "https://www.fergusonjennings.com", careers_url: "https://www.fergusonjennings.com/careers" },
  { rank: 416, name: "Ferrante & Dill LLC", hq_city: "Woodbridge", hq_state: "NJ", website_url: "https://www.ferrantedill.com", careers_url: "https://www.ferrantedill.com/careers" },
  { rank: 417, name: "Ficksman & Conley LLP", hq_city: "Boston", hq_state: "MA", website_url: "https://www.ficksmanconley.com", careers_url: "https://www.ficksmanconley.com/careers" },
  { rank: 418, name: "Fiondella, Milone & LaSaracina LLP", hq_city: "Glastonbury", hq_state: "CT", website_url: "https://www.fmlcpas.com", careers_url: "https://www.fmlcpas.com/careers" },
  { rank: 419, name: "Fischer, Taylor & Brannen", hq_city: "Louisville", hq_state: "KY", website_url: "https://www.ftbcpa.com", careers_url: "https://www.ftbcpa.com/careers" },
  { rank: 420, name: "Fisher & Company CPAs", hq_city: "Phoenix", hq_state: "AZ", website_url: "https://www.fishercpa.com", careers_url: "https://www.fishercpa.com/careers" },
  { rank: 421, name: "Fitzpatrick & Associates", hq_city: "Waukesha", hq_state: "WI", website_url: "https://www.fitzpatrickcpa.com", careers_url: "https://www.fitzpatrickcpa.com/careers" },
  { rank: 422, name: "Flanagan & Associates", hq_city: "Houston", hq_state: "TX", website_url: "https://www.flanaganassociates.com", careers_url: "https://www.flanaganassociates.com/careers" },
  { rank: 423, name: "Fleck, Jurenka & Associates", hq_city: "Des Moines", hq_state: "IA", website_url: "https://www.fleckjurenka.com", careers_url: "https://www.fleckjurenka.com/careers" },
  { rank: 424, name: "Fleming, Cornelius & Blankenship", hq_city: "Greenville", hq_state: "SC", website_url: "https://www.fcbcpa.com", careers_url: "https://www.fcbcpa.com/careers" },
  { rank: 425, name: "Fogle & Associates CPAs", hq_city: "Overland Park", hq_state: "KS", website_url: "https://www.foglecpa.com", careers_url: "https://www.foglecpa.com/careers" },
  { rank: 426, name: "Forsberg & Umlauf PS", hq_city: "Seattle", hq_state: "WA", website_url: "https://www.forsbergumlauf.com", careers_url: "https://www.forsbergumlauf.com/careers" },
  { rank: 427, name: "Foster, Garvey & Schiess", hq_city: "Seattle", hq_state: "WA", website_url: "https://www.fostergarvey.com", careers_url: "https://www.fostergarvey.com/careers" },
  { rank: 428, name: "Frazer CPAs", hq_city: "Garden City", hq_state: "NY", website_url: "https://www.frazercpa.com", careers_url: "https://www.frazercpa.com/careers" },
  { rank: 429, name: "Frisch CPAs", hq_city: "Cincinnati", hq_state: "OH", website_url: "https://www.frischcpas.com", careers_url: "https://www.frischcpas.com/careers" },
  { rank: 430, name: "Frontier Business Products", hq_city: "Sioux Falls", hq_state: "SD", website_url: "https://www.frontierbp.com", careers_url: "https://www.frontierbp.com/careers" },
  { rank: 431, name: "Frost, PLLC", hq_city: "Little Rock", hq_state: "AR", website_url: "https://www.frost.com", careers_url: "https://www.frost.com/careers" },
  { rank: 432, name: "Frost Brown Todd LLC", hq_city: "Cincinnati", hq_state: "OH", website_url: "https://www.frostbrowntodd.com", careers_url: "https://www.frostbrowntodd.com/careers" },
  { rank: 433, name: "Fruci & Associates CPAs", hq_city: "Spokane", hq_state: "WA", website_url: "https://www.fruci.com", careers_url: "https://www.fruci.com/careers" },
  { rank: 434, name: "G.T. Reilly & Company", hq_city: "Woburn", hq_state: "MA", website_url: "https://www.gtreilly.com", careers_url: "https://www.gtreilly.com/careers" },
  { rank: 435, name: "Gaedtke, Gerth & Associates", hq_city: "Milwaukee", hq_state: "WI", website_url: "https://www.ggacpa.com", careers_url: "https://www.ggacpa.com/careers" },
  { rank: 436, name: "Gainer, Donnelly & Desroches", hq_city: "Houston", hq_state: "TX", website_url: "https://www.gddcpa.com", careers_url: "https://www.gddcpa.com/careers" },
  { rank: 437, name: "Gallagher & Gallagher CPAs", hq_city: "Philadelphia", hq_state: "PA", website_url: "https://www.gallaghercpas.com", careers_url: "https://www.gallaghercpas.com/careers" },
  { rank: 438, name: "Gallun, Winter, Skwierawski & Janisse", hq_city: "Milwaukee", hq_state: "WI", website_url: "https://www.gwsjcpa.com", careers_url: "https://www.gwsjcpa.com/careers" },
  { rank: 439, name: "Gambino, Heard & Mielcarek", hq_city: "Columbus", hq_state: "OH", website_url: "https://www.ghmcpa.com", careers_url: "https://www.ghmcpa.com/careers" },
  { rank: 440, name: "Garber, Bennett & Roman", hq_city: "St. Louis", hq_state: "MO", website_url: "https://www.gbrcpa.com", careers_url: "https://www.gbrcpa.com/careers" },
  { rank: 441, name: "Garrity, Traina & Associates", hq_city: "Cleveland", hq_state: "OH", website_url: "https://www.garritycpa.com", careers_url: "https://www.garritycpa.com/careers" },
  { rank: 442, name: "Garvey Schubert Barer", hq_city: "Seattle", hq_state: "WA", website_url: "https://www.gsblaw.com", careers_url: "https://www.gsblaw.com/careers" },
  { rank: 443, name: "Gebhardt & Kiefer PC", hq_city: "Clinton", hq_state: "NJ", website_url: "https://www.gkpccpa.com", careers_url: "https://www.gkpccpa.com/careers" },
  { rank: 444, name: "Geffen Mesher CPAs", hq_city: "Portland", hq_state: "OR", website_url: "https://www.geffenmesher.com", careers_url: "https://www.geffenmesher.com/careers" },
  { rank: 445, name: "George W. Cox & Associates", hq_city: "Tucson", hq_state: "AZ", website_url: "https://www.gwcox.com", careers_url: "https://www.gwcox.com/careers" },
  { rank: 446, name: "Gibbons, Dowd & Company", hq_city: "Providence", hq_state: "RI", website_url: "https://www.gibbonsdowd.com", careers_url: "https://www.gibbonsdowd.com/careers" },
  { rank: 447, name: "Gilbane Building Company", hq_city: "Providence", hq_state: "RI", website_url: "https://www.gilbaneco.com", careers_url: "https://www.gilbaneco.com/careers" },
  { rank: 448, name: "Gilmore, Jasion & Mahler Ltd.", hq_city: "Toledo", hq_state: "OH", website_url: "https://www.gjmcpa.com", careers_url: "https://www.gjmcpa.com/careers" },
  { rank: 449, name: "Gish, Sherwood & Friends", hq_city: "Nashville", hq_state: "TN", website_url: "https://www.gishsherwood.com", careers_url: "https://www.gishsherwood.com/careers" },
  { rank: 450, name: "Glick and Trossman CPAs", hq_city: "Los Angeles", hq_state: "CA", website_url: "https://www.gtcpa.com", careers_url: "https://www.gtcpa.com/careers" },
  { rank: 451, name: "Glover & Sprague PC", hq_city: "Hartford", hq_state: "CT", website_url: "https://www.gloverspraguepc.com", careers_url: "https://www.gloverspraguepc.com/careers" },
  { rank: 452, name: "Godfrey, Hammel, Danneels & Co.", hq_city: "Traverse City", hq_state: "MI", website_url: "https://www.ghd-cpas.com", careers_url: "https://www.ghd-cpas.com/careers" },
  { rank: 453, name: "Goldstein, Golub, Kessler & Company", hq_city: "New York", hq_state: "NY", website_url: "https://www.ggkcpa.com", careers_url: "https://www.ggkcpa.com/careers" },
  { rank: 454, name: "Gonzalez, Savio, Maynard & Associates", hq_city: "Miami", hq_state: "FL", website_url: "https://www.gsmcpa.com", careers_url: "https://www.gsmcpa.com/careers" },
  { rank: 455, name: "Goodman & Company", hq_city: "Virginia Beach", hq_state: "VA", website_url: "https://www.goodmanco.com", careers_url: "https://www.goodmanco.com/careers" },
  { rank: 456, name: "Gordon, Feinblatt, Rothman, Hoffberger & Hollander", hq_city: "Baltimore", hq_state: "MD", website_url: "https://www.gfrlaw.com", careers_url: "https://www.gfrlaw.com/careers" },
  { rank: 457, name: "Gorman & Miller CPAs", hq_city: "Campbell", hq_state: "CA", website_url: "https://www.gormanmiller.com", careers_url: "https://www.gormanmiller.com/careers" },
  { rank: 458, name: "Gould Evans Associates", hq_city: "Kansas City", hq_state: "MO", website_url: "https://www.gouldevans.com", careers_url: "https://www.gouldevans.com/careers" },
  { rank: 459, name: "Graham-Pelton Consulting", hq_city: "New York", hq_state: "NY", website_url: "https://www.grahampelton.com", careers_url: "https://www.grahampelton.com/careers" },
  { rank: 460, name: "Grant, Thornton & Hendry CPAs", hq_city: "Raleigh", hq_state: "NC", website_url: "https://www.gthcpas.com", careers_url: "https://www.gthcpas.com/careers" },
  { rank: 461, name: "Gray & Creech CPAs", hq_city: "Greensboro", hq_state: "NC", website_url: "https://www.graycreech.com", careers_url: "https://www.graycreech.com/careers" },
  { rank: 462, name: "Green, Holcomb & Fisher", hq_city: "Aurora", hq_state: "CO", website_url: "https://www.ghfcpa.com", careers_url: "https://www.ghfcpa.com/careers" },
  { rank: 463, name: "Greenbaum, Rowe, Smith & Davis", hq_city: "Woodbridge", hq_state: "NJ", website_url: "https://www.greenbaumlaw.com", careers_url: "https://www.greenbaumlaw.com/careers" },
  { rank: 464, name: "Greenfield, Shapiro & Steres", hq_city: "Encino", hq_state: "CA", website_url: "https://www.gsscpa.com", careers_url: "https://www.gsscpa.com/careers" },
  { rank: 465, name: "Gregg, Boggs & Valentin", hq_city: "St. Louis", hq_state: "MO", website_url: "https://www.gbvcpa.com", careers_url: "https://www.gbvcpa.com/careers" },
  { rank: 466, name: "Gregory, Sharer & Stuart", hq_city: "St. Petersburg", hq_state: "FL", website_url: "https://www.gss-cpa.com", careers_url: "https://www.gss-cpa.com/careers" },
  { rank: 467, name: "Grierson Tobiason CPAs", hq_city: "Eugene", hq_state: "OR", website_url: "https://www.gtiorcpa.com", careers_url: "https://www.gtiorcpa.com/careers" },
  { rank: 468, name: "Griggs, Anderson, Martin & Powers", hq_city: "Dallas", hq_state: "TX", website_url: "https://www.gampcpa.com", careers_url: "https://www.gampcpa.com/careers" },
  { rank: 469, name: "Grisanti, Galef & Goldress", hq_city: "Los Angeles", hq_state: "CA", website_url: "https://www.g3cpa.com", careers_url: "https://www.g3cpa.com/careers" },
  { rank: 470, name: "Grosz & Associates", hq_city: "Encino", hq_state: "CA", website_url: "https://www.groszcpa.com", careers_url: "https://www.groszcpa.com/careers" },
  { rank: 471, name: "Gruber, Palumberi & Carosella", hq_city: "New York", hq_state: "NY", website_url: "https://www.gpcpa.com", careers_url: "https://www.gpcpa.com/careers" },
  { rank: 472, name: "Grunder Landscape Company", hq_city: "Loveland", hq_state: "OH", website_url: "https://www.grunderinc.com", careers_url: "https://www.grunderinc.com/careers" },
  { rank: 473, name: "Gschwend & Company CPAs", hq_city: "Mason", hq_state: "OH", website_url: "https://www.gschwend.com", careers_url: "https://www.gschwend.com/careers" },
  { rank: 474, name: "Guest & Brady CPAs", hq_city: "Austin", hq_state: "TX", website_url: "https://www.guestbradycpa.com", careers_url: "https://www.guestbradycpa.com/careers" },
  { rank: 475, name: "Gunn, Lee & Cave PC", hq_city: "San Antonio", hq_state: "TX", website_url: "https://www.glccpa.com", careers_url: "https://www.glccpa.com/careers" },
  { rank: 476, name: "Gursey, Schneider & Co.", hq_city: "Los Angeles", hq_state: "CA", website_url: "https://www.gscpa.com", careers_url: "https://www.gscpa.com/careers" },
  { rank: 477, name: "Gustafson & Company CPAs", hq_city: "Minneapolis", hq_state: "MN", website_url: "https://www.gustafsonco.com", careers_url: "https://www.gustafsonco.com/careers" },
  { rank: 478, name: "Guttormsen, Griffith & Norby", hq_city: "Jamestown", hq_state: "ND", website_url: "https://www.ggncpa.com", careers_url: "https://www.ggncpa.com/careers" },
  { rank: 479, name: "Hagedorn & Company", hq_city: "Alexandria", hq_state: "VA", website_url: "https://www.hagedornco.com", careers_url: "https://www.hagedornco.com/careers" },
  { rank: 480, name: "Haig, Montgomery & Bailey", hq_city: "Atlanta", hq_state: "GA", website_url: "https://www.hmbcpa.com", careers_url: "https://www.hmbcpa.com/careers" },
  { rank: 481, name: "Hamlin, Scanlon & Associates", hq_city: "Boston", hq_state: "MA", website_url: "https://www.hamlinscanlon.com", careers_url: "https://www.hamlinscanlon.com/careers" },
  { rank: 482, name: "Hampton, Sherrod & Martzolf", hq_city: "Charlotte", hq_state: "NC", website_url: "https://www.hsmcpas.com", careers_url: "https://www.hsmcpas.com/careers" },
  { rank: 483, name: "Hannis T. Bourgeois LLP", hq_city: "Baton Rouge", hq_state: "LA", website_url: "https://www.htbcpa.com", careers_url: "https://www.htbcpa.com/careers" },
  { rank: 484, name: "Hanson, Walter & Associates", hq_city: "Fargo", hq_state: "ND", website_url: "https://www.hwacpa.com", careers_url: "https://www.hwacpa.com/careers" },
  { rank: 485, name: "Harding & Associates CPAs", hq_city: "Walnut Creek", hq_state: "CA", website_url: "https://www.hardingcpa.com", careers_url: "https://www.hardingcpa.com/careers" },
  { rank: 486, name: "Hardwick & Morris PC", hq_city: "Jackson", hq_state: "MS", website_url: "https://www.hardwickmorris.com", careers_url: "https://www.hardwickmorris.com/careers" },
  { rank: 487, name: "Harker Hurley & Associates", hq_city: "Fresno", hq_state: "CA", website_url: "https://www.hhacpa.com", careers_url: "https://www.hhacpa.com/careers" },
  { rank: 488, name: "Harley-Davidson Financial Services", hq_city: "Milwaukee", hq_state: "WI", website_url: "https://www.harley-davidson.com", careers_url: "https://careers.harley-davidson.com" },
  { rank: 489, name: "Harper, Rains, Knight & Company", hq_city: "Ridgeland", hq_state: "MS", website_url: "https://www.hrknightcpa.com", careers_url: "https://www.hrknightcpa.com/careers" },
  { rank: 490, name: "Harris, Hardy & Johnsen PC", hq_city: "Idaho Falls", hq_state: "ID", website_url: "https://www.hhjcpa.com", careers_url: "https://www.hhjcpa.com/careers" },
  { rank: 491, name: "Hartman, Leito & Bolt LLP", hq_city: "Amarillo", hq_state: "TX", website_url: "https://www.hlbcpa.com", careers_url: "https://www.hlbcpa.com/careers" },
  { rank: 492, name: "Harvey Watt & Company", hq_city: "Atlanta", hq_state: "GA", website_url: "https://www.harveywatt.com", careers_url: "https://www.harveywatt.com/careers" },
  { rank: 493, name: "Haskins & Sells", hq_city: "New York", hq_state: "NY", website_url: "https://www.deloitte.com", careers_url: "https://www.deloitte.com/us/en/careers.html" },
  { rank: 494, name: "Hastings Prince CPAs", hq_city: "Spokane", hq_state: "WA", website_url: "https://www.hastingsprince.com", careers_url: "https://www.hastingsprince.com/careers" },
  { rank: 495, name: "Hatfield & Watkins", hq_city: "Charlotte", hq_state: "NC", website_url: "https://www.hwcpa.com", careers_url: "https://www.hwcpa.com/careers" },
  { rank: 496, name: "Haugen, Johnson & Associates", hq_city: "Grand Forks", hq_state: "ND", website_url: "https://www.hjacpa.com", careers_url: "https://www.hjacpa.com/careers" },
  { rank: 497, name: "Hayashi Wayland", hq_city: "Salinas", hq_state: "CA", website_url: "https://www.hayashiwayland.com", careers_url: "https://www.hayashiwayland.com/careers" },
  { rank: 498, name: "Haynes, Downard, Beste & Weil", hq_city: "Indianapolis", hq_state: "IN", website_url: "https://www.hdbwcpa.com", careers_url: "https://www.hdbwcpa.com/careers" },
  { rank: 499, name: "Health Management Systems", hq_city: "New York", hq_state: "NY", website_url: "https://www.hms.com", careers_url: "https://www.hms.com/careers" },
  { rank: 500, name: "Heard, McElroy & Vestal LLC", hq_city: "Shreveport", hq_state: "LA", website_url: "https://www.heardmcelroy.com", careers_url: "https://www.heardmcelroy.com/careers" },
];

async function main() {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");

    // Ensure unique constraint exists on name
    await client.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint
          WHERE conname = 'firms_name_unique' AND conrelid = 'firms'::regclass
        ) THEN
          ALTER TABLE firms ADD CONSTRAINT firms_name_unique UNIQUE (name);
        END IF;
      END$$;
    `);

    let inserted = 0;
    let skipped = 0;

    for (const firm of FIRMS) {
      const result = await client.query(
        `INSERT INTO firms (name, rank, hq_city, hq_state, website_url, careers_url, ats_type, ats_url)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
         ON CONFLICT (name) DO NOTHING
         RETURNING id`,
        [
          firm.name,
          firm.rank,
          firm.hq_city,
          firm.hq_state,
          firm.website_url,
          firm.careers_url,
          firm.ats_type ?? "unknown",
          firm.ats_url ?? null,
        ]
      );
      if (result.rowCount && result.rowCount > 0) {
        inserted++;
      } else {
        skipped++;
      }
    }

    await client.query("COMMIT");
    console.log(`Done. Inserted: ${inserted}, Skipped (already exist): ${skipped}`);
  } catch (err) {
    await client.query("ROLLBACK");
    console.error("Seed failed:", err);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

main();
